package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bebeasociado generated by hbm2java
 */
@Entity
@Table(name="bebeasociado"
    ,schema="public"
)
public class Bebeasociado  implements java.io.Serializable {


     private BebeasociadoId id;
     private Consentimiento consentimiento;
     private String dni;
     private String apellynombrebebeasociado;
     private Set seguimientobebeasociados = new HashSet(0);

    public Bebeasociado() {
    }

	
    public Bebeasociado(BebeasociadoId id, Consentimiento consentimiento, String dni) {
        this.id = id;
        this.consentimiento = consentimiento;
        this.dni = dni;
    }
    public Bebeasociado(BebeasociadoId id, Consentimiento consentimiento, String dni, String apellynombrebebeasociado, Set seguimientobebeasociados) {
       this.id = id;
       this.consentimiento = consentimiento;
       this.dni = dni;
       this.apellynombrebebeasociado = apellynombrebebeasociado;
       this.seguimientobebeasociados = seguimientobebeasociados;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idbebeasociado", column=@Column(name="idbebeasociado", nullable=false) ), 
        @AttributeOverride(name="nroconcentimiento", column=@Column(name="nroconcentimiento", nullable=false) ) } )
    public BebeasociadoId getId() {
        return this.id;
    }
    
    public void setId(BebeasociadoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nroconcentimiento", nullable=false, insertable=false, updatable=false)
    public Consentimiento getConsentimiento() {
        return this.consentimiento;
    }
    
    public void setConsentimiento(Consentimiento consentimiento) {
        this.consentimiento = consentimiento;
    }

    
    @Column(name="dni", nullable=false, length=10)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="apellynombrebebeasociado", length=25)
    public String getApellynombrebebeasociado() {
        return this.apellynombrebebeasociado;
    }
    
    public void setApellynombrebebeasociado(String apellynombrebebeasociado) {
        this.apellynombrebebeasociado = apellynombrebebeasociado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bebeasociado")
    public Set getSeguimientobebeasociados() {
        return this.seguimientobebeasociados;
    }
    
    public void setSeguimientobebeasociados(Set seguimientobebeasociados) {
        this.seguimientobebeasociados = seguimientobebeasociados;
    }




}


