package org.blh.habilitacion.entities;
// Generated 30-jun-2015 0:45:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BebeasociadoId generated by hbm2java
 */
@Embeddable
public class BebeasociadoId  implements java.io.Serializable {


     private int idBebeAosciado;
     private int nroConcentimiento;

    public BebeasociadoId() {
    }

    public BebeasociadoId(int idBebeAosciado, int nroConcentimiento) {
       this.idBebeAosciado = idBebeAosciado;
       this.nroConcentimiento = nroConcentimiento;
    }
   


    @Column(name="idBebeAosciado", nullable=false)
    public int getIdBebeAosciado() {
        return this.idBebeAosciado;
    }
    
    public void setIdBebeAosciado(int idBebeAosciado) {
        this.idBebeAosciado = idBebeAosciado;
    }


    @Column(name="nroConcentimiento", nullable=false)
    public int getNroConcentimiento() {
        return this.nroConcentimiento;
    }
    
    public void setNroConcentimiento(int nroConcentimiento) {
        this.nroConcentimiento = nroConcentimiento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BebeasociadoId) ) return false;
		 BebeasociadoId castOther = ( BebeasociadoId ) other; 
         
		 return (this.getIdBebeAosciado()==castOther.getIdBebeAosciado())
 && (this.getNroConcentimiento()==castOther.getNroConcentimiento());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdBebeAosciado();
         result = 37 * result + this.getNroConcentimiento();
         return result;
   }   


}


