package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bebereceptor generated by hbm2java
 */
@Entity
@Table(name="bebereceptor"
    ,schema="public"
)
public class Bebereceptor  implements java.io.Serializable {


     private int idbebereceptor;
     private String dnibebereceptor;
     private String apellynombrebebereceptor;
     private Date fehcadenac;
     private String lugarnac;
     private String nombremadre;
     private String nombrepadre;
     private String direccion;
     private Boolean consumolechebanco;
     private String motnoconsumo;
     private Set fraccionamientos = new HashSet(0);
     private Set seguimientobebereceptors = new HashSet(0);

    public Bebereceptor() {
    }

	
    public Bebereceptor(int idbebereceptor, String nombremadre) {
        this.idbebereceptor = idbebereceptor;
        this.nombremadre = nombremadre;
    }
    public Bebereceptor(int idbebereceptor, String dnibebereceptor, String apellynombrebebereceptor, Date fehcadenac, String lugarnac, String nombremadre, String nombrepadre, String direccion, Boolean consumolechebanco, String motnoconsumo, Set fraccionamientos, Set seguimientobebereceptors) {
       this.idbebereceptor = idbebereceptor;
       this.dnibebereceptor = dnibebereceptor;
       this.apellynombrebebereceptor = apellynombrebebereceptor;
       this.fehcadenac = fehcadenac;
       this.lugarnac = lugarnac;
       this.nombremadre = nombremadre;
       this.nombrepadre = nombrepadre;
       this.direccion = direccion;
       this.consumolechebanco = consumolechebanco;
       this.motnoconsumo = motnoconsumo;
       this.fraccionamientos = fraccionamientos;
       this.seguimientobebereceptors = seguimientobebereceptors;
    }
   
     @Id 

    
    @Column(name="idbebereceptor", unique=true, nullable=false)
    public int getIdbebereceptor() {
        return this.idbebereceptor;
    }
    
    public void setIdbebereceptor(int idbebereceptor) {
        this.idbebereceptor = idbebereceptor;
    }

    
    @Column(name="dnibebereceptor", length=10)
    public String getDnibebereceptor() {
        return this.dnibebereceptor;
    }
    
    public void setDnibebereceptor(String dnibebereceptor) {
        this.dnibebereceptor = dnibebereceptor;
    }

    
    @Column(name="apellynombrebebereceptor", length=25)
    public String getApellynombrebebereceptor() {
        return this.apellynombrebebereceptor;
    }
    
    public void setApellynombrebebereceptor(String apellynombrebebereceptor) {
        this.apellynombrebebereceptor = apellynombrebebereceptor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fehcadenac", length=13)
    public Date getFehcadenac() {
        return this.fehcadenac;
    }
    
    public void setFehcadenac(Date fehcadenac) {
        this.fehcadenac = fehcadenac;
    }

    
    @Column(name="lugarnac", length=25)
    public String getLugarnac() {
        return this.lugarnac;
    }
    
    public void setLugarnac(String lugarnac) {
        this.lugarnac = lugarnac;
    }

    
    @Column(name="nombremadre", nullable=false, length=18)
    public String getNombremadre() {
        return this.nombremadre;
    }
    
    public void setNombremadre(String nombremadre) {
        this.nombremadre = nombremadre;
    }

    
    @Column(name="nombrepadre", length=10)
    public String getNombrepadre() {
        return this.nombrepadre;
    }
    
    public void setNombrepadre(String nombrepadre) {
        this.nombrepadre = nombrepadre;
    }

    
    @Column(name="direccion", length=10)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="consumolechebanco")
    public Boolean getConsumolechebanco() {
        return this.consumolechebanco;
    }
    
    public void setConsumolechebanco(Boolean consumolechebanco) {
        this.consumolechebanco = consumolechebanco;
    }

    
    @Column(name="motnoconsumo", length=30)
    public String getMotnoconsumo() {
        return this.motnoconsumo;
    }
    
    public void setMotnoconsumo(String motnoconsumo) {
        this.motnoconsumo = motnoconsumo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bebereceptor")
    public Set getFraccionamientos() {
        return this.fraccionamientos;
    }
    
    public void setFraccionamientos(Set fraccionamientos) {
        this.fraccionamientos = fraccionamientos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bebereceptor")
    public Set getSeguimientobebereceptors() {
        return this.seguimientobebereceptors;
    }
    
    public void setSeguimientobebereceptors(Set seguimientobebereceptors) {
        this.seguimientobebereceptors = seguimientobebereceptors;
    }




}


