package org.blh.habilitacion.entities;
// Generated 30-jun-2015 0:45:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bebereceptor generated by hbm2java
 */
@Entity
@Table(name="bebereceptor"
    ,schema="public"
)
public class Bebereceptor  implements java.io.Serializable {


     private int idBebeReceptor;
     private String dniBebeReceptor;
     private String apellyNombreBebeReceptor;
     private Date fehcaDeNac;
     private String lugarNac;
     private String nombreMade;
     private String nombrePadre;
     private String direccion;
     private Boolean consumoLecheBanco;
     private String motNoConsumo;
     private Set fraccionamientos = new HashSet(0);
     private Set seguimientobebereceptors = new HashSet(0);

    public Bebereceptor() {
    }

	
    public Bebereceptor(int idBebeReceptor, String nombreMade) {
        this.idBebeReceptor = idBebeReceptor;
        this.nombreMade = nombreMade;
    }
    public Bebereceptor(int idBebeReceptor, String dniBebeReceptor, String apellyNombreBebeReceptor, Date fehcaDeNac, String lugarNac, String nombreMade, String nombrePadre, String direccion, Boolean consumoLecheBanco, String motNoConsumo, Set fraccionamientos, Set seguimientobebereceptors) {
       this.idBebeReceptor = idBebeReceptor;
       this.dniBebeReceptor = dniBebeReceptor;
       this.apellyNombreBebeReceptor = apellyNombreBebeReceptor;
       this.fehcaDeNac = fehcaDeNac;
       this.lugarNac = lugarNac;
       this.nombreMade = nombreMade;
       this.nombrePadre = nombrePadre;
       this.direccion = direccion;
       this.consumoLecheBanco = consumoLecheBanco;
       this.motNoConsumo = motNoConsumo;
       this.fraccionamientos = fraccionamientos;
       this.seguimientobebereceptors = seguimientobebereceptors;
    }
   
     @Id 

    
    @Column(name="idBebeReceptor", nullable=false)
    public int getIdBebeReceptor() {
        return this.idBebeReceptor;
    }
    
    public void setIdBebeReceptor(int idBebeReceptor) {
        this.idBebeReceptor = idBebeReceptor;
    }

    
    @Column(name="dniBebeReceptor", length=10)
    public String getDniBebeReceptor() {
        return this.dniBebeReceptor;
    }
    
    public void setDniBebeReceptor(String dniBebeReceptor) {
        this.dniBebeReceptor = dniBebeReceptor;
    }

    
    @Column(name="apellyNombreBebeReceptor", length=25)
    public String getApellyNombreBebeReceptor() {
        return this.apellyNombreBebeReceptor;
    }
    
    public void setApellyNombreBebeReceptor(String apellyNombreBebeReceptor) {
        this.apellyNombreBebeReceptor = apellyNombreBebeReceptor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fehcaDeNac", length=13)
    public Date getFehcaDeNac() {
        return this.fehcaDeNac;
    }
    
    public void setFehcaDeNac(Date fehcaDeNac) {
        this.fehcaDeNac = fehcaDeNac;
    }

    
    @Column(name="lugarNac", length=25)
    public String getLugarNac() {
        return this.lugarNac;
    }
    
    public void setLugarNac(String lugarNac) {
        this.lugarNac = lugarNac;
    }

    
    @Column(name="nombreMade", nullable=false, length=18)
    public String getNombreMade() {
        return this.nombreMade;
    }
    
    public void setNombreMade(String nombreMade) {
        this.nombreMade = nombreMade;
    }

    
    @Column(name="nombrePadre", length=10)
    public String getNombrePadre() {
        return this.nombrePadre;
    }
    
    public void setNombrePadre(String nombrePadre) {
        this.nombrePadre = nombrePadre;
    }

    
    @Column(name="direccion", length=10)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="consumoLecheBanco")
    public Boolean getConsumoLecheBanco() {
        return this.consumoLecheBanco;
    }
    
    public void setConsumoLecheBanco(Boolean consumoLecheBanco) {
        this.consumoLecheBanco = consumoLecheBanco;
    }

    
    @Column(name="motNoConsumo", length=30)
    public String getMotNoConsumo() {
        return this.motNoConsumo;
    }
    
    public void setMotNoConsumo(String motNoConsumo) {
        this.motNoConsumo = motNoConsumo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bebereceptor")
    public Set getFraccionamientos() {
        return this.fraccionamientos;
    }
    
    public void setFraccionamientos(Set fraccionamientos) {
        this.fraccionamientos = fraccionamientos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bebereceptor")
    public Set getSeguimientobebereceptors() {
        return this.seguimientobebereceptors;
    }
    
    public void setSeguimientobebereceptors(Set seguimientobebereceptors) {
        this.seguimientobebereceptors = seguimientobebereceptors;
    }




}


