package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BebeasociadoId generated by hbm2java
 */
@Embeddable
public class BebeasociadoId  implements java.io.Serializable {


     private int idbebeasociado;
     private int nroconcentimiento;

    public BebeasociadoId() {
    }

    public BebeasociadoId(int idbebeasociado, int nroconcentimiento) {
       this.idbebeasociado = idbebeasociado;
       this.nroconcentimiento = nroconcentimiento;
    }
   


    @Column(name="idbebeasociado", nullable=false)
    public int getIdbebeasociado() {
        return this.idbebeasociado;
    }
    
    public void setIdbebeasociado(int idbebeasociado) {
        this.idbebeasociado = idbebeasociado;
    }


    @Column(name="nroconcentimiento", nullable=false)
    public int getNroconcentimiento() {
        return this.nroconcentimiento;
    }
    
    public void setNroconcentimiento(int nroconcentimiento) {
        this.nroconcentimiento = nroconcentimiento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BebeasociadoId) ) return false;
		 BebeasociadoId castOther = ( BebeasociadoId ) other; 
         
		 return (this.getIdbebeasociado()==castOther.getIdbebeasociado())
 && (this.getNroconcentimiento()==castOther.getNroconcentimiento());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdbebeasociado();
         result = 37 * result + this.getNroconcentimiento();
         return result;
   }   


}


