package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Biberon generated by hbm2java
 */
@Entity
@Table(name="biberon"
    ,schema="public"
)
public class Biberon  implements java.io.Serializable {


     private int idbiberon;
     private Pasteurizacion pasteurizacion;
     private Double volumendeleche;
     private Double tipodeleche;
     private Double hematocritos;
     private Double crema;
     private Double totalcol;
     private Double gordura;
     private Double kcalxl;
     private Double cultivocal24;
     private Double cultivocal48;
     private Boolean estado;
     private String motivorechazo;
     private Set entregadebiberonacentros = new HashSet(0);
     private Set fraccionamientos = new HashSet(0);
     private Set frascoses = new HashSet(0);

    public Biberon() {
    }

	
    public Biberon(int idbiberon, Pasteurizacion pasteurizacion) {
        this.idbiberon = idbiberon;
        this.pasteurizacion = pasteurizacion;
    }
    public Biberon(int idbiberon, Pasteurizacion pasteurizacion, Double volumendeleche, Double tipodeleche, Double hematocritos, Double crema, Double totalcol, Double gordura, Double kcalxl, Double cultivocal24, Double cultivocal48, Boolean estado, String motivorechazo, Set entregadebiberonacentros, Set fraccionamientos, Set frascoses) {
       this.idbiberon = idbiberon;
       this.pasteurizacion = pasteurizacion;
       this.volumendeleche = volumendeleche;
       this.tipodeleche = tipodeleche;
       this.hematocritos = hematocritos;
       this.crema = crema;
       this.totalcol = totalcol;
       this.gordura = gordura;
       this.kcalxl = kcalxl;
       this.cultivocal24 = cultivocal24;
       this.cultivocal48 = cultivocal48;
       this.estado = estado;
       this.motivorechazo = motivorechazo;
       this.entregadebiberonacentros = entregadebiberonacentros;
       this.fraccionamientos = fraccionamientos;
       this.frascoses = frascoses;
    }
   
     @Id 

    
    @Column(name="idbiberon", unique=true, nullable=false)
    public int getIdbiberon() {
        return this.idbiberon;
    }
    
    public void setIdbiberon(int idbiberon) {
        this.idbiberon = idbiberon;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpasteurizacion", nullable=false)
    public Pasteurizacion getPasteurizacion() {
        return this.pasteurizacion;
    }
    
    public void setPasteurizacion(Pasteurizacion pasteurizacion) {
        this.pasteurizacion = pasteurizacion;
    }

    
    @Column(name="volumendeleche", precision=17, scale=17)
    public Double getVolumendeleche() {
        return this.volumendeleche;
    }
    
    public void setVolumendeleche(Double volumendeleche) {
        this.volumendeleche = volumendeleche;
    }

    
    @Column(name="tipodeleche", precision=17, scale=17)
    public Double getTipodeleche() {
        return this.tipodeleche;
    }
    
    public void setTipodeleche(Double tipodeleche) {
        this.tipodeleche = tipodeleche;
    }

    
    @Column(name="hematocritos", precision=17, scale=17)
    public Double getHematocritos() {
        return this.hematocritos;
    }
    
    public void setHematocritos(Double hematocritos) {
        this.hematocritos = hematocritos;
    }

    
    @Column(name="crema", precision=17, scale=17)
    public Double getCrema() {
        return this.crema;
    }
    
    public void setCrema(Double crema) {
        this.crema = crema;
    }

    
    @Column(name="totalcol", precision=17, scale=17)
    public Double getTotalcol() {
        return this.totalcol;
    }
    
    public void setTotalcol(Double totalcol) {
        this.totalcol = totalcol;
    }

    
    @Column(name="gordura", precision=17, scale=17)
    public Double getGordura() {
        return this.gordura;
    }
    
    public void setGordura(Double gordura) {
        this.gordura = gordura;
    }

    
    @Column(name="kcalxl", precision=17, scale=17)
    public Double getKcalxl() {
        return this.kcalxl;
    }
    
    public void setKcalxl(Double kcalxl) {
        this.kcalxl = kcalxl;
    }

    
    @Column(name="cultivocal24", precision=17, scale=17)
    public Double getCultivocal24() {
        return this.cultivocal24;
    }
    
    public void setCultivocal24(Double cultivocal24) {
        this.cultivocal24 = cultivocal24;
    }

    
    @Column(name="cultivocal48", precision=17, scale=17)
    public Double getCultivocal48() {
        return this.cultivocal48;
    }
    
    public void setCultivocal48(Double cultivocal48) {
        this.cultivocal48 = cultivocal48;
    }

    
    @Column(name="estado")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    
    @Column(name="motivorechazo", length=50)
    public String getMotivorechazo() {
        return this.motivorechazo;
    }
    
    public void setMotivorechazo(String motivorechazo) {
        this.motivorechazo = motivorechazo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="biberon")
    public Set getEntregadebiberonacentros() {
        return this.entregadebiberonacentros;
    }
    
    public void setEntregadebiberonacentros(Set entregadebiberonacentros) {
        this.entregadebiberonacentros = entregadebiberonacentros;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="biberon")
    public Set getFraccionamientos() {
        return this.fraccionamientos;
    }
    
    public void setFraccionamientos(Set fraccionamientos) {
        this.fraccionamientos = fraccionamientos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="biberon")
    public Set getFrascoses() {
        return this.frascoses;
    }
    
    public void setFrascoses(Set frascoses) {
        this.frascoses = frascoses;
    }




}


