package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Centros generated by hbm2java
 */
@Entity
@Table(name="centros"
    ,schema="public"
)
public class Centros  implements java.io.Serializable {


     private int idcentro;
     private String nombrecentro;
     private String domiciliocentro;
     private String telefonocentro;
     private Set consentimientos = new HashSet(0);
     private Set entregadebiberonacentros = new HashSet(0);

    public Centros() {
    }

	
    public Centros(int idcentro) {
        this.idcentro = idcentro;
    }
    public Centros(int idcentro, String nombrecentro, String domiciliocentro, String telefonocentro, Set consentimientos, Set entregadebiberonacentros) {
       this.idcentro = idcentro;
       this.nombrecentro = nombrecentro;
       this.domiciliocentro = domiciliocentro;
       this.telefonocentro = telefonocentro;
       this.consentimientos = consentimientos;
       this.entregadebiberonacentros = entregadebiberonacentros;
    }
   
     @Id 

    
    @Column(name="idcentro", unique=true, nullable=false)
    public int getIdcentro() {
        return this.idcentro;
    }
    
    public void setIdcentro(int idcentro) {
        this.idcentro = idcentro;
    }

    
    @Column(name="nombrecentro", length=30)
    public String getNombrecentro() {
        return this.nombrecentro;
    }
    
    public void setNombrecentro(String nombrecentro) {
        this.nombrecentro = nombrecentro;
    }

    
    @Column(name="domiciliocentro", length=30)
    public String getDomiciliocentro() {
        return this.domiciliocentro;
    }
    
    public void setDomiciliocentro(String domiciliocentro) {
        this.domiciliocentro = domiciliocentro;
    }

    
    @Column(name="telefonocentro", length=15)
    public String getTelefonocentro() {
        return this.telefonocentro;
    }
    
    public void setTelefonocentro(String telefonocentro) {
        this.telefonocentro = telefonocentro;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="centros")
    public Set getConsentimientos() {
        return this.consentimientos;
    }
    
    public void setConsentimientos(Set consentimientos) {
        this.consentimientos = consentimientos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="centros")
    public Set getEntregadebiberonacentros() {
        return this.entregadebiberonacentros;
    }
    
    public void setEntregadebiberonacentros(Set entregadebiberonacentros) {
        this.entregadebiberonacentros = entregadebiberonacentros;
    }




}


