package org.blh.habilitacion.entities;
// Generated 30-jun-2015 0:45:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Centros generated by hbm2java
 */
@Entity
@Table(name="centros"
    ,schema="public"
)
public class Centros  implements java.io.Serializable {


     private int idCentro;
     private String nombreCentro;
     private String domicilioCentro;
     private String telefonoCentro;
     private Set consentimientos = new HashSet(0);
     private Set entregadebiberonacentros = new HashSet(0);

    public Centros() {
    }

	
    public Centros(int idCentro) {
        this.idCentro = idCentro;
    }
    public Centros(int idCentro, String nombreCentro, String domicilioCentro, String telefonoCentro, Set consentimientos, Set entregadebiberonacentros) {
       this.idCentro = idCentro;
       this.nombreCentro = nombreCentro;
       this.domicilioCentro = domicilioCentro;
       this.telefonoCentro = telefonoCentro;
       this.consentimientos = consentimientos;
       this.entregadebiberonacentros = entregadebiberonacentros;
    }
   
     @Id 

    
    @Column(name="idCentro", nullable=false)
    public int getIdCentro() {
        return this.idCentro;
    }
    
    public void setIdCentro(int idCentro) {
        this.idCentro = idCentro;
    }

    
    @Column(name="nombreCentro", length=30)
    public String getNombreCentro() {
        return this.nombreCentro;
    }
    
    public void setNombreCentro(String nombreCentro) {
        this.nombreCentro = nombreCentro;
    }

    
    @Column(name="domicilioCentro", length=30)
    public String getDomicilioCentro() {
        return this.domicilioCentro;
    }
    
    public void setDomicilioCentro(String domicilioCentro) {
        this.domicilioCentro = domicilioCentro;
    }

    
    @Column(name="telefonoCentro", length=15)
    public String getTelefonoCentro() {
        return this.telefonoCentro;
    }
    
    public void setTelefonoCentro(String telefonoCentro) {
        this.telefonoCentro = telefonoCentro;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="centros")
    public Set getConsentimientos() {
        return this.consentimientos;
    }
    
    public void setConsentimientos(Set consentimientos) {
        this.consentimientos = consentimientos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="centros")
    public Set getEntregadebiberonacentros() {
        return this.entregadebiberonacentros;
    }
    
    public void setEntregadebiberonacentros(Set entregadebiberonacentros) {
        this.entregadebiberonacentros = entregadebiberonacentros;
    }




}


