package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Consentimiento generated by hbm2java
 */
@Entity
@Table(name="consentimiento"
    ,schema="public"
)
public class Consentimiento  implements java.io.Serializable {


     private int nroconcentimiento;
     private Centros centros;
     private Donante donante;
     private Zona zona;
     private Date fechadesde;
     private Date fechahasta;
     private Date diasyhorarios;
     private Date fechnacbebeasociado;
     private Long edadgestacionalbebeasociado;
     private Date lugarnacbebeasociado;
     private String calle;
     private Integer altura;
     private String barrio;
     private String pc;
     private String mz;
     private String piso;
     private String departamento;
     private Long permitefotos;
     private Integer cantfrascos;
     private String motcierreconsentimiento;
     private Set consentimientoxhrs = new HashSet(0);
     private Set serologias = new HashSet(0);
     private Set bebeasociados = new HashSet(0);

    public Consentimiento() {
    }

	
    public Consentimiento(int nroconcentimiento, Donante donante, Zona zona) {
        this.nroconcentimiento = nroconcentimiento;
        this.donante = donante;
        this.zona = zona;
    }
    public Consentimiento(int nroconcentimiento, Centros centros, Donante donante, Zona zona, Date fechadesde, Date fechahasta, Date diasyhorarios, Date fechnacbebeasociado, Long edadgestacionalbebeasociado, Date lugarnacbebeasociado, String calle, Integer altura, String barrio, String pc, String mz, String piso, String departamento, Long permitefotos, Integer cantfrascos, String motcierreconsentimiento, Set consentimientoxhrs, Set serologias, Set bebeasociados) {
       this.nroconcentimiento = nroconcentimiento;
       this.centros = centros;
       this.donante = donante;
       this.zona = zona;
       this.fechadesde = fechadesde;
       this.fechahasta = fechahasta;
       this.diasyhorarios = diasyhorarios;
       this.fechnacbebeasociado = fechnacbebeasociado;
       this.edadgestacionalbebeasociado = edadgestacionalbebeasociado;
       this.lugarnacbebeasociado = lugarnacbebeasociado;
       this.calle = calle;
       this.altura = altura;
       this.barrio = barrio;
       this.pc = pc;
       this.mz = mz;
       this.piso = piso;
       this.departamento = departamento;
       this.permitefotos = permitefotos;
       this.cantfrascos = cantfrascos;
       this.motcierreconsentimiento = motcierreconsentimiento;
       this.consentimientoxhrs = consentimientoxhrs;
       this.serologias = serologias;
       this.bebeasociados = bebeasociados;
    }
   
     @Id 

    
    @Column(name="nroconcentimiento", unique=true, nullable=false)
    public int getNroconcentimiento() {
        return this.nroconcentimiento;
    }
    
    public void setNroconcentimiento(int nroconcentimiento) {
        this.nroconcentimiento = nroconcentimiento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcentro")
    public Centros getCentros() {
        return this.centros;
    }
    
    public void setCentros(Centros centros) {
        this.centros = centros;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nrodonante", nullable=false)
    public Donante getDonante() {
        return this.donante;
    }
    
    public void setDonante(Donante donante) {
        this.donante = donante;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="idzona", referencedColumnName="idzona", nullable=false), 
        @JoinColumn(name="idlocalidad", referencedColumnName="idlocalidad", nullable=false), 
        @JoinColumn(name="idprovincia", referencedColumnName="idprovincia", nullable=false) } )
    public Zona getZona() {
        return this.zona;
    }
    
    public void setZona(Zona zona) {
        this.zona = zona;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechadesde", length=13)
    public Date getFechadesde() {
        return this.fechadesde;
    }
    
    public void setFechadesde(Date fechadesde) {
        this.fechadesde = fechadesde;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechahasta", length=13)
    public Date getFechahasta() {
        return this.fechahasta;
    }
    
    public void setFechahasta(Date fechahasta) {
        this.fechahasta = fechahasta;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="diasyhorarios", length=29)
    public Date getDiasyhorarios() {
        return this.diasyhorarios;
    }
    
    public void setDiasyhorarios(Date diasyhorarios) {
        this.diasyhorarios = diasyhorarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechnacbebeasociado", length=13)
    public Date getFechnacbebeasociado() {
        return this.fechnacbebeasociado;
    }
    
    public void setFechnacbebeasociado(Date fechnacbebeasociado) {
        this.fechnacbebeasociado = fechnacbebeasociado;
    }

    
    @Column(name="edadgestacionalbebeasociado", precision=10, scale=0)
    public Long getEdadgestacionalbebeasociado() {
        return this.edadgestacionalbebeasociado;
    }
    
    public void setEdadgestacionalbebeasociado(Long edadgestacionalbebeasociado) {
        this.edadgestacionalbebeasociado = edadgestacionalbebeasociado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lugarnacbebeasociado", length=13)
    public Date getLugarnacbebeasociado() {
        return this.lugarnacbebeasociado;
    }
    
    public void setLugarnacbebeasociado(Date lugarnacbebeasociado) {
        this.lugarnacbebeasociado = lugarnacbebeasociado;
    }

    
    @Column(name="calle", length=25)
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }

    
    @Column(name="altura")
    public Integer getAltura() {
        return this.altura;
    }
    
    public void setAltura(Integer altura) {
        this.altura = altura;
    }

    
    @Column(name="barrio", length=10)
    public String getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }

    
    @Column(name="pc", length=10)
    public String getPc() {
        return this.pc;
    }
    
    public void setPc(String pc) {
        this.pc = pc;
    }

    
    @Column(name="mz", length=10)
    public String getMz() {
        return this.mz;
    }
    
    public void setMz(String mz) {
        this.mz = mz;
    }

    
    @Column(name="piso", length=10)
    public String getPiso() {
        return this.piso;
    }
    
    public void setPiso(String piso) {
        this.piso = piso;
    }

    
    @Column(name="departamento", length=10)
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="permitefotos")
    public Long getPermitefotos() {
        return this.permitefotos;
    }
    
    public void setPermitefotos(Long permitefotos) {
        this.permitefotos = permitefotos;
    }

    
    @Column(name="cantfrascos")
    public Integer getCantfrascos() {
        return this.cantfrascos;
    }
    
    public void setCantfrascos(Integer cantfrascos) {
        this.cantfrascos = cantfrascos;
    }

    
    @Column(name="motcierreconsentimiento", length=30)
    public String getMotcierreconsentimiento() {
        return this.motcierreconsentimiento;
    }
    
    public void setMotcierreconsentimiento(String motcierreconsentimiento) {
        this.motcierreconsentimiento = motcierreconsentimiento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consentimiento")
    public Set getConsentimientoxhrs() {
        return this.consentimientoxhrs;
    }
    
    public void setConsentimientoxhrs(Set consentimientoxhrs) {
        this.consentimientoxhrs = consentimientoxhrs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consentimiento")
    public Set getSerologias() {
        return this.serologias;
    }
    
    public void setSerologias(Set serologias) {
        this.serologias = serologias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consentimiento")
    public Set getBebeasociados() {
        return this.bebeasociados;
    }
    
    public void setBebeasociados(Set bebeasociados) {
        this.bebeasociados = bebeasociados;
    }




}


