package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Consentimientoxhr generated by hbm2java
 */
@Entity
@Table(name="consentimientoxhr"
    ,schema="public"
)
public class Consentimientoxhr  implements java.io.Serializable {


     private ConsentimientoxhrId id;
     private Consentimiento consentimiento;
     private Hojaderuta hojaderuta;
     private Integer cantfrascosentregados;
     private Integer cantfrascosrecolectados;
     private String observaciones;
     private Set frascoses = new HashSet(0);

    public Consentimientoxhr() {
    }

	
    public Consentimientoxhr(ConsentimientoxhrId id, Consentimiento consentimiento, Hojaderuta hojaderuta) {
        this.id = id;
        this.consentimiento = consentimiento;
        this.hojaderuta = hojaderuta;
    }
    public Consentimientoxhr(ConsentimientoxhrId id, Consentimiento consentimiento, Hojaderuta hojaderuta, Integer cantfrascosentregados, Integer cantfrascosrecolectados, String observaciones, Set frascoses) {
       this.id = id;
       this.consentimiento = consentimiento;
       this.hojaderuta = hojaderuta;
       this.cantfrascosentregados = cantfrascosentregados;
       this.cantfrascosrecolectados = cantfrascosrecolectados;
       this.observaciones = observaciones;
       this.frascoses = frascoses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="nroconcentimiento", column=@Column(name="nroconcentimiento", nullable=false) ), 
        @AttributeOverride(name="idhojaderuta", column=@Column(name="idhojaderuta", nullable=false) ) } )
    public ConsentimientoxhrId getId() {
        return this.id;
    }
    
    public void setId(ConsentimientoxhrId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nroconcentimiento", nullable=false, insertable=false, updatable=false)
    public Consentimiento getConsentimiento() {
        return this.consentimiento;
    }
    
    public void setConsentimiento(Consentimiento consentimiento) {
        this.consentimiento = consentimiento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idhojaderuta", nullable=false, insertable=false, updatable=false)
    public Hojaderuta getHojaderuta() {
        return this.hojaderuta;
    }
    
    public void setHojaderuta(Hojaderuta hojaderuta) {
        this.hojaderuta = hojaderuta;
    }

    
    @Column(name="cantfrascosentregados")
    public Integer getCantfrascosentregados() {
        return this.cantfrascosentregados;
    }
    
    public void setCantfrascosentregados(Integer cantfrascosentregados) {
        this.cantfrascosentregados = cantfrascosentregados;
    }

    
    @Column(name="cantfrascosrecolectados")
    public Integer getCantfrascosrecolectados() {
        return this.cantfrascosrecolectados;
    }
    
    public void setCantfrascosrecolectados(Integer cantfrascosrecolectados) {
        this.cantfrascosrecolectados = cantfrascosrecolectados;
    }

    
    @Column(name="observaciones", length=30)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consentimientoxhr")
    public Set getFrascoses() {
        return this.frascoses;
    }
    
    public void setFrascoses(Set frascoses) {
        this.frascoses = frascoses;
    }




}


