package org.blh.habilitacion.entities;
// Generated 30-jun-2015 0:45:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConsentimientoxhrId generated by hbm2java
 */
@Embeddable
public class ConsentimientoxhrId  implements java.io.Serializable {


     private int nroConcentimiento;
     private int idHojadeRuta;

    public ConsentimientoxhrId() {
    }

    public ConsentimientoxhrId(int nroConcentimiento, int idHojadeRuta) {
       this.nroConcentimiento = nroConcentimiento;
       this.idHojadeRuta = idHojadeRuta;
    }
   


    @Column(name="nroConcentimiento", nullable=false)
    public int getNroConcentimiento() {
        return this.nroConcentimiento;
    }
    
    public void setNroConcentimiento(int nroConcentimiento) {
        this.nroConcentimiento = nroConcentimiento;
    }


    @Column(name="idHojadeRuta", nullable=false)
    public int getIdHojadeRuta() {
        return this.idHojadeRuta;
    }
    
    public void setIdHojadeRuta(int idHojadeRuta) {
        this.idHojadeRuta = idHojadeRuta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConsentimientoxhrId) ) return false;
		 ConsentimientoxhrId castOther = ( ConsentimientoxhrId ) other; 
         
		 return (this.getNroConcentimiento()==castOther.getNroConcentimiento())
 && (this.getIdHojadeRuta()==castOther.getIdHojadeRuta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNroConcentimiento();
         result = 37 * result + this.getIdHojadeRuta();
         return result;
   }   


}


