package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConsentimientoxhrId generated by hbm2java
 */
@Embeddable
public class ConsentimientoxhrId  implements java.io.Serializable {


     private int nroconcentimiento;
     private int idhojaderuta;

    public ConsentimientoxhrId() {
    }

    public ConsentimientoxhrId(int nroconcentimiento, int idhojaderuta) {
       this.nroconcentimiento = nroconcentimiento;
       this.idhojaderuta = idhojaderuta;
    }
   


    @Column(name="nroconcentimiento", nullable=false)
    public int getNroconcentimiento() {
        return this.nroconcentimiento;
    }
    
    public void setNroconcentimiento(int nroconcentimiento) {
        this.nroconcentimiento = nroconcentimiento;
    }


    @Column(name="idhojaderuta", nullable=false)
    public int getIdhojaderuta() {
        return this.idhojaderuta;
    }
    
    public void setIdhojaderuta(int idhojaderuta) {
        this.idhojaderuta = idhojaderuta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConsentimientoxhrId) ) return false;
		 ConsentimientoxhrId castOther = ( ConsentimientoxhrId ) other; 
         
		 return (this.getNroconcentimiento()==castOther.getNroconcentimiento())
 && (this.getIdhojaderuta()==castOther.getIdhojaderuta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNroconcentimiento();
         result = 37 * result + this.getIdhojaderuta();
         return result;
   }   


}


