package org.blh.habilitacion.entities;
// Generated 30-jun-2015 0:45:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Consentimientoxhr generated by hbm2java
 */
@Entity
@Table(name="consentimientoxhr"
    ,schema="public"
)
public class Consentimientoxhr  implements java.io.Serializable {


     private ConsentimientoxhrId id;
     private Consentimiento consentimiento;
     private Hojaderuta hojaderuta;
     private Integer cantFrascosEntregados;
     private Integer cantFrascosRecolectados;
     private String observaciones;
     private Set frascoses = new HashSet(0);

    public Consentimientoxhr() {
    }

	
    public Consentimientoxhr(ConsentimientoxhrId id, Consentimiento consentimiento, Hojaderuta hojaderuta) {
        this.id = id;
        this.consentimiento = consentimiento;
        this.hojaderuta = hojaderuta;
    }
    public Consentimientoxhr(ConsentimientoxhrId id, Consentimiento consentimiento, Hojaderuta hojaderuta, Integer cantFrascosEntregados, Integer cantFrascosRecolectados, String observaciones, Set frascoses) {
       this.id = id;
       this.consentimiento = consentimiento;
       this.hojaderuta = hojaderuta;
       this.cantFrascosEntregados = cantFrascosEntregados;
       this.cantFrascosRecolectados = cantFrascosRecolectados;
       this.observaciones = observaciones;
       this.frascoses = frascoses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="nroConcentimiento", column=@Column(name="nroConcentimiento", nullable=false) ), 
        @AttributeOverride(name="idHojadeRuta", column=@Column(name="idHojadeRuta", nullable=false) ) } )
    public ConsentimientoxhrId getId() {
        return this.id;
    }
    
    public void setId(ConsentimientoxhrId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nroConcentimiento", nullable=false, insertable=false, updatable=false)
    public Consentimiento getConsentimiento() {
        return this.consentimiento;
    }
    
    public void setConsentimiento(Consentimiento consentimiento) {
        this.consentimiento = consentimiento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idHojadeRuta", nullable=false, insertable=false, updatable=false)
    public Hojaderuta getHojaderuta() {
        return this.hojaderuta;
    }
    
    public void setHojaderuta(Hojaderuta hojaderuta) {
        this.hojaderuta = hojaderuta;
    }

    
    @Column(name="cantFrascosEntregados")
    public Integer getCantFrascosEntregados() {
        return this.cantFrascosEntregados;
    }
    
    public void setCantFrascosEntregados(Integer cantFrascosEntregados) {
        this.cantFrascosEntregados = cantFrascosEntregados;
    }

    
    @Column(name="cantFrascosRecolectados")
    public Integer getCantFrascosRecolectados() {
        return this.cantFrascosRecolectados;
    }
    
    public void setCantFrascosRecolectados(Integer cantFrascosRecolectados) {
        this.cantFrascosRecolectados = cantFrascosRecolectados;
    }

    
    @Column(name="observaciones", length=30)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="consentimientoxhr")
    public Set getFrascoses() {
        return this.frascoses;
    }
    
    public void setFrascoses(Set frascoses) {
        this.frascoses = frascoses;
    }




}


