package org.blh.habilitacion.entities;
// Generated 30-jun-2015 0:45:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Donante generated by hbm2java
 */
@Entity
@Table(name="donante"
    ,schema="public"
)
public class Donante  implements java.io.Serializable {


     private int nroDonante;
     private Medios medios;
     private String apellyNombreDonante;
     private String dni;
     private Date fechNac;
     private String telefono;
     private String estadoCivil;
     private String ocupacion;
     private String nivelEstudio;
     private String email;
     private String tipoDonante;
     private Set consentimientos = new HashSet(0);

    public Donante() {
    }

	
    public Donante(int nroDonante, Medios medios, String apellyNombreDonante, String dni) {
        this.nroDonante = nroDonante;
        this.medios = medios;
        this.apellyNombreDonante = apellyNombreDonante;
        this.dni = dni;
    }
    public Donante(int nroDonante, Medios medios, String apellyNombreDonante, String dni, Date fechNac, String telefono, String estadoCivil, String ocupacion, String nivelEstudio, String email, String tipoDonante, Set consentimientos) {
       this.nroDonante = nroDonante;
       this.medios = medios;
       this.apellyNombreDonante = apellyNombreDonante;
       this.dni = dni;
       this.fechNac = fechNac;
       this.telefono = telefono;
       this.estadoCivil = estadoCivil;
       this.ocupacion = ocupacion;
       this.nivelEstudio = nivelEstudio;
       this.email = email;
       this.tipoDonante = tipoDonante;
       this.consentimientos = consentimientos;
    }
   
     @Id 

    
    @Column(name="nroDonante", nullable=false)
    public int getNroDonante() {
        return this.nroDonante;
    }
    
    public void setNroDonante(int nroDonante) {
        this.nroDonante = nroDonante;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMedios", nullable=false)
    public Medios getMedios() {
        return this.medios;
    }
    
    public void setMedios(Medios medios) {
        this.medios = medios;
    }

    
    @Column(name="apellyNombreDonante", nullable=false, length=30)
    public String getApellyNombreDonante() {
        return this.apellyNombreDonante;
    }
    
    public void setApellyNombreDonante(String apellyNombreDonante) {
        this.apellyNombreDonante = apellyNombreDonante;
    }

    
    @Column(name="dni", nullable=false, length=10)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechNac", length=13)
    public Date getFechNac() {
        return this.fechNac;
    }
    
    public void setFechNac(Date fechNac) {
        this.fechNac = fechNac;
    }

    
    @Column(name="telefono", length=15)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="estadoCivil", length=10)
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    
    @Column(name="ocupacion", length=30)
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }

    
    @Column(name="nivelEstudio", length=20)
    public String getNivelEstudio() {
        return this.nivelEstudio;
    }
    
    public void setNivelEstudio(String nivelEstudio) {
        this.nivelEstudio = nivelEstudio;
    }

    
    @Column(name="email", length=20)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="tipoDonante", length=15)
    public String getTipoDonante() {
        return this.tipoDonante;
    }
    
    public void setTipoDonante(String tipoDonante) {
        this.tipoDonante = tipoDonante;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="donante")
    public Set getConsentimientos() {
        return this.consentimientos;
    }
    
    public void setConsentimientos(Set consentimientos) {
        this.consentimientos = consentimientos;
    }




}


