package org.blh.habilitacion.entities;
// Generated 30-jun-2015 0:45:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EntregadebiberonacentroId generated by hbm2java
 */
@Embeddable
public class EntregadebiberonacentroId  implements java.io.Serializable {


     private int idCentro;
     private int idBiberon;

    public EntregadebiberonacentroId() {
    }

    public EntregadebiberonacentroId(int idCentro, int idBiberon) {
       this.idCentro = idCentro;
       this.idBiberon = idBiberon;
    }
   


    @Column(name="idCentro", nullable=false)
    public int getIdCentro() {
        return this.idCentro;
    }
    
    public void setIdCentro(int idCentro) {
        this.idCentro = idCentro;
    }


    @Column(name="idBiberon", nullable=false)
    public int getIdBiberon() {
        return this.idBiberon;
    }
    
    public void setIdBiberon(int idBiberon) {
        this.idBiberon = idBiberon;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EntregadebiberonacentroId) ) return false;
		 EntregadebiberonacentroId castOther = ( EntregadebiberonacentroId ) other; 
         
		 return (this.getIdCentro()==castOther.getIdCentro())
 && (this.getIdBiberon()==castOther.getIdBiberon());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCentro();
         result = 37 * result + this.getIdBiberon();
         return result;
   }   


}


