package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EntregadebiberonacentroId generated by hbm2java
 */
@Embeddable
public class EntregadebiberonacentroId  implements java.io.Serializable {


     private int idcentro;
     private int idbiberon;

    public EntregadebiberonacentroId() {
    }

    public EntregadebiberonacentroId(int idcentro, int idbiberon) {
       this.idcentro = idcentro;
       this.idbiberon = idbiberon;
    }
   


    @Column(name="idcentro", nullable=false)
    public int getIdcentro() {
        return this.idcentro;
    }
    
    public void setIdcentro(int idcentro) {
        this.idcentro = idcentro;
    }


    @Column(name="idbiberon", nullable=false)
    public int getIdbiberon() {
        return this.idbiberon;
    }
    
    public void setIdbiberon(int idbiberon) {
        this.idbiberon = idbiberon;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EntregadebiberonacentroId) ) return false;
		 EntregadebiberonacentroId castOther = ( EntregadebiberonacentroId ) other; 
         
		 return (this.getIdcentro()==castOther.getIdcentro())
 && (this.getIdbiberon()==castOther.getIdbiberon());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdcentro();
         result = 37 * result + this.getIdbiberon();
         return result;
   }   


}


