package org.blh.habilitacion.entities;
// Generated 30-jun-2015 0:45:21 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fraccionamiento generated by hbm2java
 */
@Entity
@Table(name="fraccionamiento"
    ,schema="public"
)
public class Fraccionamiento  implements java.io.Serializable {


     private FraccionamientoId id;
     private Bebereceptor bebereceptor;
     private Biberon biberon;
     private Date fechFraccionamiento;
     private String prescNutricionista;
     private Double volumen;
     private Double consumido;
     private String motNoConsumo;

    public Fraccionamiento() {
    }

	
    public Fraccionamiento(FraccionamientoId id, Bebereceptor bebereceptor, Biberon biberon) {
        this.id = id;
        this.bebereceptor = bebereceptor;
        this.biberon = biberon;
    }
    public Fraccionamiento(FraccionamientoId id, Bebereceptor bebereceptor, Biberon biberon, Date fechFraccionamiento, String prescNutricionista, Double volumen, Double consumido, String motNoConsumo) {
       this.id = id;
       this.bebereceptor = bebereceptor;
       this.biberon = biberon;
       this.fechFraccionamiento = fechFraccionamiento;
       this.prescNutricionista = prescNutricionista;
       this.volumen = volumen;
       this.consumido = consumido;
       this.motNoConsumo = motNoConsumo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idFraccionamiento", column=@Column(name="idFraccionamiento", nullable=false) ), 
        @AttributeOverride(name="idBebeReceptor", column=@Column(name="idBebeReceptor", nullable=false) ), 
        @AttributeOverride(name="idBiberon", column=@Column(name="idBiberon", nullable=false) ) } )
    public FraccionamientoId getId() {
        return this.id;
    }
    
    public void setId(FraccionamientoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idBebeReceptor", nullable=false, insertable=false, updatable=false)
    public Bebereceptor getBebereceptor() {
        return this.bebereceptor;
    }
    
    public void setBebereceptor(Bebereceptor bebereceptor) {
        this.bebereceptor = bebereceptor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idBiberon", nullable=false, insertable=false, updatable=false)
    public Biberon getBiberon() {
        return this.biberon;
    }
    
    public void setBiberon(Biberon biberon) {
        this.biberon = biberon;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechFraccionamiento", length=13)
    public Date getFechFraccionamiento() {
        return this.fechFraccionamiento;
    }
    
    public void setFechFraccionamiento(Date fechFraccionamiento) {
        this.fechFraccionamiento = fechFraccionamiento;
    }

    
    @Column(name="prescNutricionista", length=10)
    public String getPrescNutricionista() {
        return this.prescNutricionista;
    }
    
    public void setPrescNutricionista(String prescNutricionista) {
        this.prescNutricionista = prescNutricionista;
    }

    
    @Column(name="volumen", precision=17, scale=17)
    public Double getVolumen() {
        return this.volumen;
    }
    
    public void setVolumen(Double volumen) {
        this.volumen = volumen;
    }

    
    @Column(name="consumido", precision=17, scale=17)
    public Double getConsumido() {
        return this.consumido;
    }
    
    public void setConsumido(Double consumido) {
        this.consumido = consumido;
    }

    
    @Column(name="motNoConsumo", length=30)
    public String getMotNoConsumo() {
        return this.motNoConsumo;
    }
    
    public void setMotNoConsumo(String motNoConsumo) {
        this.motNoConsumo = motNoConsumo;
    }




}


