package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FraccionamientoId generated by hbm2java
 */
@Embeddable
public class FraccionamientoId  implements java.io.Serializable {


     private int idfraccionamiento;
     private int idbebereceptor;
     private int idbiberon;

    public FraccionamientoId() {
    }

    public FraccionamientoId(int idfraccionamiento, int idbebereceptor, int idbiberon) {
       this.idfraccionamiento = idfraccionamiento;
       this.idbebereceptor = idbebereceptor;
       this.idbiberon = idbiberon;
    }
   


    @Column(name="idfraccionamiento", nullable=false)
    public int getIdfraccionamiento() {
        return this.idfraccionamiento;
    }
    
    public void setIdfraccionamiento(int idfraccionamiento) {
        this.idfraccionamiento = idfraccionamiento;
    }


    @Column(name="idbebereceptor", nullable=false)
    public int getIdbebereceptor() {
        return this.idbebereceptor;
    }
    
    public void setIdbebereceptor(int idbebereceptor) {
        this.idbebereceptor = idbebereceptor;
    }


    @Column(name="idbiberon", nullable=false)
    public int getIdbiberon() {
        return this.idbiberon;
    }
    
    public void setIdbiberon(int idbiberon) {
        this.idbiberon = idbiberon;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FraccionamientoId) ) return false;
		 FraccionamientoId castOther = ( FraccionamientoId ) other; 
         
		 return (this.getIdfraccionamiento()==castOther.getIdfraccionamiento())
 && (this.getIdbebereceptor()==castOther.getIdbebereceptor())
 && (this.getIdbiberon()==castOther.getIdbiberon());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdfraccionamiento();
         result = 37 * result + this.getIdbebereceptor();
         result = 37 * result + this.getIdbiberon();
         return result;
   }   


}


