package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Frascos generated by hbm2java
 */
@Entity
@Table(name="frascos"
    ,schema="public"
)
public class Frascos  implements java.io.Serializable {


     private int nrofrasco;
     private Biberon biberon;
     private Consentimientoxhr consentimientoxhr;
     private Date fechaextracion;
     private String tipodeleche;
     private String estadodefrasco;
     private String volumendeleche;
     private Double niveldeacides;
     private Double hematocritos;
     private Boolean estadoFrasco;
     private String motrechazofrasco;

    public Frascos() {
    }

	
    public Frascos(int nrofrasco, Biberon biberon, Consentimientoxhr consentimientoxhr) {
        this.nrofrasco = nrofrasco;
        this.biberon = biberon;
        this.consentimientoxhr = consentimientoxhr;
    }
    public Frascos(int nrofrasco, Biberon biberon, Consentimientoxhr consentimientoxhr, Date fechaextracion, String tipodeleche, String estadodefrasco, String volumendeleche, Double niveldeacides, Double hematocritos, Boolean estadoFrasco, String motrechazofrasco) {
       this.nrofrasco = nrofrasco;
       this.biberon = biberon;
       this.consentimientoxhr = consentimientoxhr;
       this.fechaextracion = fechaextracion;
       this.tipodeleche = tipodeleche;
       this.estadodefrasco = estadodefrasco;
       this.volumendeleche = volumendeleche;
       this.niveldeacides = niveldeacides;
       this.hematocritos = hematocritos;
       this.estadoFrasco = estadoFrasco;
       this.motrechazofrasco = motrechazofrasco;
    }
   
     @Id 

    
    @Column(name="nrofrasco", unique=true, nullable=false)
    public int getNrofrasco() {
        return this.nrofrasco;
    }
    
    public void setNrofrasco(int nrofrasco) {
        this.nrofrasco = nrofrasco;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idbiberon", nullable=false)
    public Biberon getBiberon() {
        return this.biberon;
    }
    
    public void setBiberon(Biberon biberon) {
        this.biberon = biberon;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="nroconcentimiento", referencedColumnName="nroconcentimiento", nullable=false), 
        @JoinColumn(name="idhojaderuta", referencedColumnName="idhojaderuta", nullable=false) } )
    public Consentimientoxhr getConsentimientoxhr() {
        return this.consentimientoxhr;
    }
    
    public void setConsentimientoxhr(Consentimientoxhr consentimientoxhr) {
        this.consentimientoxhr = consentimientoxhr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaextracion", length=13)
    public Date getFechaextracion() {
        return this.fechaextracion;
    }
    
    public void setFechaextracion(Date fechaextracion) {
        this.fechaextracion = fechaextracion;
    }

    
    @Column(name="tipodeleche", length=10)
    public String getTipodeleche() {
        return this.tipodeleche;
    }
    
    public void setTipodeleche(String tipodeleche) {
        this.tipodeleche = tipodeleche;
    }

    
    @Column(name="estadodefrasco", length=10)
    public String getEstadodefrasco() {
        return this.estadodefrasco;
    }
    
    public void setEstadodefrasco(String estadodefrasco) {
        this.estadodefrasco = estadodefrasco;
    }

    
    @Column(name="volumendeleche", length=10)
    public String getVolumendeleche() {
        return this.volumendeleche;
    }
    
    public void setVolumendeleche(String volumendeleche) {
        this.volumendeleche = volumendeleche;
    }

    
    @Column(name="niveldeacides", precision=17, scale=17)
    public Double getNiveldeacides() {
        return this.niveldeacides;
    }
    
    public void setNiveldeacides(Double niveldeacides) {
        this.niveldeacides = niveldeacides;
    }

    
    @Column(name="hematocritos", precision=17, scale=17)
    public Double getHematocritos() {
        return this.hematocritos;
    }
    
    public void setHematocritos(Double hematocritos) {
        this.hematocritos = hematocritos;
    }

    
    @Column(name="estadoFrasco")
    public Boolean getEstadoFrasco() {
        return this.estadoFrasco;
    }
    
    public void setEstadoFrasco(Boolean estadoFrasco) {
        this.estadoFrasco = estadoFrasco;
    }

    
    @Column(name="motrechazofrasco", length=25)
    public String getMotrechazofrasco() {
        return this.motrechazofrasco;
    }
    
    public void setMotrechazofrasco(String motrechazofrasco) {
        this.motrechazofrasco = motrechazofrasco;
    }




}


