package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hojaderuta generated by hbm2java
 */
@Entity
@Table(name="hojaderuta"
    ,schema="public"
)
public class Hojaderuta  implements java.io.Serializable {


     private int idhojaderuta;
     private Date feccreacionhdr;
     private Date fecrecorrido;
     private String chofer;
     private String asistente;
     private String observaciones;
     private Set consentimientoxhrs = new HashSet(0);

    public Hojaderuta() {
    }

	
    public Hojaderuta(int idhojaderuta) {
        this.idhojaderuta = idhojaderuta;
    }
    public Hojaderuta(int idhojaderuta, Date feccreacionhdr, Date fecrecorrido, String chofer, String asistente, String observaciones, Set consentimientoxhrs) {
       this.idhojaderuta = idhojaderuta;
       this.feccreacionhdr = feccreacionhdr;
       this.fecrecorrido = fecrecorrido;
       this.chofer = chofer;
       this.asistente = asistente;
       this.observaciones = observaciones;
       this.consentimientoxhrs = consentimientoxhrs;
    }
   
     @Id 

    
    @Column(name="idhojaderuta", unique=true, nullable=false)
    public int getIdhojaderuta() {
        return this.idhojaderuta;
    }
    
    public void setIdhojaderuta(int idhojaderuta) {
        this.idhojaderuta = idhojaderuta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="feccreacionhdr", length=13)
    public Date getFeccreacionhdr() {
        return this.feccreacionhdr;
    }
    
    public void setFeccreacionhdr(Date feccreacionhdr) {
        this.feccreacionhdr = feccreacionhdr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecrecorrido", length=13)
    public Date getFecrecorrido() {
        return this.fecrecorrido;
    }
    
    public void setFecrecorrido(Date fecrecorrido) {
        this.fecrecorrido = fecrecorrido;
    }

    
    @Column(name="chofer", length=25)
    public String getChofer() {
        return this.chofer;
    }
    
    public void setChofer(String chofer) {
        this.chofer = chofer;
    }

    
    @Column(name="asistente", length=25)
    public String getAsistente() {
        return this.asistente;
    }
    
    public void setAsistente(String asistente) {
        this.asistente = asistente;
    }

    
    @Column(name="observaciones", length=30)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hojaderuta")
    public Set getConsentimientoxhrs() {
        return this.consentimientoxhrs;
    }
    
    public void setConsentimientoxhrs(Set consentimientoxhrs) {
        this.consentimientoxhrs = consentimientoxhrs;
    }




}


