package org.blh.habilitacion.entities;
// Generated 30-jun-2015 0:45:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hojaderuta generated by hbm2java
 */
@Entity
@Table(name="hojaderuta"
    ,schema="public"
)
public class Hojaderuta  implements java.io.Serializable {


     private int idHojadeRuta;
     private Date fecCreacionHdR;
     private Date fecRecorrido;
     private String chofer;
     private String asistente;
     private String observaciones;
     private Set consentimientoxhrs = new HashSet(0);

    public Hojaderuta() {
    }

	
    public Hojaderuta(int idHojadeRuta) {
        this.idHojadeRuta = idHojadeRuta;
    }
    public Hojaderuta(int idHojadeRuta, Date fecCreacionHdR, Date fecRecorrido, String chofer, String asistente, String observaciones, Set consentimientoxhrs) {
       this.idHojadeRuta = idHojadeRuta;
       this.fecCreacionHdR = fecCreacionHdR;
       this.fecRecorrido = fecRecorrido;
       this.chofer = chofer;
       this.asistente = asistente;
       this.observaciones = observaciones;
       this.consentimientoxhrs = consentimientoxhrs;
    }
   
     @Id 

    
    @Column(name="idHojadeRuta", nullable=false)
    public int getIdHojadeRuta() {
        return this.idHojadeRuta;
    }
    
    public void setIdHojadeRuta(int idHojadeRuta) {
        this.idHojadeRuta = idHojadeRuta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecCreacionHdR", length=13)
    public Date getFecCreacionHdR() {
        return this.fecCreacionHdR;
    }
    
    public void setFecCreacionHdR(Date fecCreacionHdR) {
        this.fecCreacionHdR = fecCreacionHdR;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecRecorrido", length=13)
    public Date getFecRecorrido() {
        return this.fecRecorrido;
    }
    
    public void setFecRecorrido(Date fecRecorrido) {
        this.fecRecorrido = fecRecorrido;
    }

    
    @Column(name="chofer", length=25)
    public String getChofer() {
        return this.chofer;
    }
    
    public void setChofer(String chofer) {
        this.chofer = chofer;
    }

    
    @Column(name="asistente", length=25)
    public String getAsistente() {
        return this.asistente;
    }
    
    public void setAsistente(String asistente) {
        this.asistente = asistente;
    }

    
    @Column(name="observaciones", length=30)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hojaderuta")
    public Set getConsentimientoxhrs() {
        return this.consentimientoxhrs;
    }
    
    public void setConsentimientoxhrs(Set consentimientoxhrs) {
        this.consentimientoxhrs = consentimientoxhrs;
    }




}


