package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocalidadId generated by hbm2java
 */
@Embeddable
public class LocalidadId  implements java.io.Serializable {


     private int idlocalidad;
     private int idprovincia;

    public LocalidadId() {
    }

    public LocalidadId(int idlocalidad, int idprovincia) {
       this.idlocalidad = idlocalidad;
       this.idprovincia = idprovincia;
    }
   


    @Column(name="idlocalidad", nullable=false)
    public int getIdlocalidad() {
        return this.idlocalidad;
    }
    
    public void setIdlocalidad(int idlocalidad) {
        this.idlocalidad = idlocalidad;
    }


    @Column(name="idprovincia", nullable=false)
    public int getIdprovincia() {
        return this.idprovincia;
    }
    
    public void setIdprovincia(int idprovincia) {
        this.idprovincia = idprovincia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LocalidadId) ) return false;
		 LocalidadId castOther = ( LocalidadId ) other; 
         
		 return (this.getIdlocalidad()==castOther.getIdlocalidad())
 && (this.getIdprovincia()==castOther.getIdprovincia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdlocalidad();
         result = 37 * result + this.getIdprovincia();
         return result;
   }   


}


