package org.blh.habilitacion.entities;
// Generated 30-jun-2015 0:45:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Localidad generated by hbm2java
 */
@Entity
@Table(name="localidad"
    ,schema="public"
)
public class Localidad  implements java.io.Serializable {


     private int idLocalidad;
     private Provincia provincia;
     private String nombreLocalidad;
     private Integer cp;
     private Set zonas = new HashSet(0);

    public Localidad() {
    }

	
    public Localidad(int idLocalidad, Provincia provincia, String nombreLocalidad) {
        this.idLocalidad = idLocalidad;
        this.provincia = provincia;
        this.nombreLocalidad = nombreLocalidad;
    }
    public Localidad(int idLocalidad, Provincia provincia, String nombreLocalidad, Integer cp, Set zonas) {
       this.idLocalidad = idLocalidad;
       this.provincia = provincia;
       this.nombreLocalidad = nombreLocalidad;
       this.cp = cp;
       this.zonas = zonas;
    }
   
     @Id 

    
    @Column(name="idLocalidad", nullable=false)
    public int getIdLocalidad() {
        return this.idLocalidad;
    }
    
    public void setIdLocalidad(int idLocalidad) {
        this.idLocalidad = idLocalidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProvincia", nullable=false)
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }

    
    @Column(name="nombreLocalidad", nullable=false, length=30)
    public String getNombreLocalidad() {
        return this.nombreLocalidad;
    }
    
    public void setNombreLocalidad(String nombreLocalidad) {
        this.nombreLocalidad = nombreLocalidad;
    }

    
    @Column(name="cp")
    public Integer getCp() {
        return this.cp;
    }
    
    public void setCp(Integer cp) {
        this.cp = cp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="localidad")
    public Set getZonas() {
        return this.zonas;
    }
    
    public void setZonas(Set zonas) {
        this.zonas = zonas;
    }




}


