package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Localidad generated by hbm2java
 */
@Entity
@Table(name="localidad"
    ,schema="public"
)
public class Localidad  implements java.io.Serializable {


     private LocalidadId id;
     private Provincia provincia;
     private String nombreLocalidad;
     private Integer cp;
     private Set zonas = new HashSet(0);

    public Localidad() {
    }

	
    public Localidad(LocalidadId id, Provincia provincia, String nombreLocalidad) {
        this.id = id;
        this.provincia = provincia;
        this.nombreLocalidad = nombreLocalidad;
    }
    public Localidad(LocalidadId id, Provincia provincia, String nombreLocalidad, Integer cp, Set zonas) {
       this.id = id;
       this.provincia = provincia;
       this.nombreLocalidad = nombreLocalidad;
       this.cp = cp;
       this.zonas = zonas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idlocalidad", column=@Column(name="idlocalidad", nullable=false) ), 
        @AttributeOverride(name="idprovincia", column=@Column(name="idprovincia", nullable=false) ) } )
    public LocalidadId getId() {
        return this.id;
    }
    
    public void setId(LocalidadId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idprovincia", nullable=false, insertable=false, updatable=false)
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }

    
    @Column(name="nombreLocalidad", nullable=false, length=30)
    public String getNombreLocalidad() {
        return this.nombreLocalidad;
    }
    
    public void setNombreLocalidad(String nombreLocalidad) {
        this.nombreLocalidad = nombreLocalidad;
    }

    
    @Column(name="cp")
    public Integer getCp() {
        return this.cp;
    }
    
    public void setCp(Integer cp) {
        this.cp = cp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="localidad")
    public Set getZonas() {
        return this.zonas;
    }
    
    public void setZonas(Set zonas) {
        this.zonas = zonas;
    }




}


