package org.blh.habilitacion.entities;
// Generated 30-jun-2015 0:45:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Medios generated by hbm2java
 */
@Entity
@Table(name="medios"
    ,schema="public"
)
public class Medios  implements java.io.Serializable {


     private int idMedios;
     private String nombreMedio;
     private Boolean estadoMedio;
     private Set donantes = new HashSet(0);

    public Medios() {
    }

	
    public Medios(int idMedios, String nombreMedio) {
        this.idMedios = idMedios;
        this.nombreMedio = nombreMedio;
    }
    public Medios(int idMedios, String nombreMedio, Boolean estadoMedio, Set donantes) {
       this.idMedios = idMedios;
       this.nombreMedio = nombreMedio;
       this.estadoMedio = estadoMedio;
       this.donantes = donantes;
    }
   
     @Id 

    
    @Column(name="idMedios", nullable=false)
    public int getIdMedios() {
        return this.idMedios;
    }
    
    public void setIdMedios(int idMedios) {
        this.idMedios = idMedios;
    }

    
    @Column(name="nombreMedio", nullable=false, length=15)
    public String getNombreMedio() {
        return this.nombreMedio;
    }
    
    public void setNombreMedio(String nombreMedio) {
        this.nombreMedio = nombreMedio;
    }

    
    @Column(name="estadoMedio")
    public Boolean getEstadoMedio() {
        return this.estadoMedio;
    }
    
    public void setEstadoMedio(Boolean estadoMedio) {
        this.estadoMedio = estadoMedio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medios")
    public Set getDonantes() {
        return this.donantes;
    }
    
    public void setDonantes(Set donantes) {
        this.donantes = donantes;
    }




}


