package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Medios generated by hbm2java
 */
@Entity
@Table(name="medios"
    ,schema="public"
)
public class Medios  implements java.io.Serializable {


     private int idmedios;
     private String nombremedio;
     private Boolean estadomedio;
     private Set donantes = new HashSet(0);

    public Medios() {
    }

	
    public Medios(int idmedios, String nombremedio) {
        this.idmedios = idmedios;
        this.nombremedio = nombremedio;
    }
    public Medios(int idmedios, String nombremedio, Boolean estadomedio, Set donantes) {
       this.idmedios = idmedios;
       this.nombremedio = nombremedio;
       this.estadomedio = estadomedio;
       this.donantes = donantes;
    }
   
     @Id 

    
    @Column(name="idmedios", unique=true, nullable=false)
    public int getIdmedios() {
        return this.idmedios;
    }
    
    public void setIdmedios(int idmedios) {
        this.idmedios = idmedios;
    }

    
    @Column(name="nombremedio", nullable=false, length=15)
    public String getNombremedio() {
        return this.nombremedio;
    }
    
    public void setNombremedio(String nombremedio) {
        this.nombremedio = nombremedio;
    }

    
    @Column(name="estadomedio")
    public Boolean getEstadomedio() {
        return this.estadomedio;
    }
    
    public void setEstadomedio(Boolean estadomedio) {
        this.estadomedio = estadomedio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medios")
    public Set getDonantes() {
        return this.donantes;
    }
    
    public void setDonantes(Set donantes) {
        this.donantes = donantes;
    }




}


