package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pasteurizacion generated by hbm2java
 */
@Entity
@Table(name="pasteurizacion"
    ,schema="public"
)
public class Pasteurizacion  implements java.io.Serializable {


     private int idpasteurizacion;
     private Date fechapasteurizacion;
     private String responsable;
     private String confirmacion;
     private Set biberons = new HashSet(0);

    public Pasteurizacion() {
    }

	
    public Pasteurizacion(int idpasteurizacion, String responsable) {
        this.idpasteurizacion = idpasteurizacion;
        this.responsable = responsable;
    }
    public Pasteurizacion(int idpasteurizacion, Date fechapasteurizacion, String responsable, String confirmacion, Set biberons) {
       this.idpasteurizacion = idpasteurizacion;
       this.fechapasteurizacion = fechapasteurizacion;
       this.responsable = responsable;
       this.confirmacion = confirmacion;
       this.biberons = biberons;
    }
   
     @Id 

    
    @Column(name="idpasteurizacion", unique=true, nullable=false)
    public int getIdpasteurizacion() {
        return this.idpasteurizacion;
    }
    
    public void setIdpasteurizacion(int idpasteurizacion) {
        this.idpasteurizacion = idpasteurizacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechapasteurizacion", length=13)
    public Date getFechapasteurizacion() {
        return this.fechapasteurizacion;
    }
    
    public void setFechapasteurizacion(Date fechapasteurizacion) {
        this.fechapasteurizacion = fechapasteurizacion;
    }

    
    @Column(name="responsable", nullable=false, length=18)
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }

    
    @Column(name="confirmacion", length=10)
    public String getConfirmacion() {
        return this.confirmacion;
    }
    
    public void setConfirmacion(String confirmacion) {
        this.confirmacion = confirmacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pasteurizacion")
    public Set getBiberons() {
        return this.biberons;
    }
    
    public void setBiberons(Set biberons) {
        this.biberons = biberons;
    }




}


