package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name="provincia"
    ,schema="public"
)
public class Provincia  implements java.io.Serializable {


     private int idprovincia;
     private String nombreProvincia;
     private Set localidads = new HashSet(0);

    public Provincia() {
    }

	
    public Provincia(int idprovincia, String nombreProvincia) {
        this.idprovincia = idprovincia;
        this.nombreProvincia = nombreProvincia;
    }
    public Provincia(int idprovincia, String nombreProvincia, Set localidads) {
       this.idprovincia = idprovincia;
       this.nombreProvincia = nombreProvincia;
       this.localidads = localidads;
    }
   
     @Id 

    
    @Column(name="idprovincia", unique=true, nullable=false)
    public int getIdprovincia() {
        return this.idprovincia;
    }
    
    public void setIdprovincia(int idprovincia) {
        this.idprovincia = idprovincia;
    }

    
    @Column(name="nombreProvincia", nullable=false, length=30)
    public String getNombreProvincia() {
        return this.nombreProvincia;
    }
    
    public void setNombreProvincia(String nombreProvincia) {
        this.nombreProvincia = nombreProvincia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="provincia")
    public Set getLocalidads() {
        return this.localidads;
    }
    
    public void setLocalidads(Set localidads) {
        this.localidads = localidads;
    }




}


