package org.blh.habilitacion.entities;
// Generated 30-jun-2015 0:45:21 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name="provincia"
    ,schema="public"
)
public class Provincia  implements java.io.Serializable {


     private int idprovincia;
     private String nombreprovincia;
     private Set localidads = new HashSet(0);

    public Provincia() {
    }

	
    public Provincia(int idprovincia, String nombreprovincia) {
        this.idprovincia = idprovincia;
        this.nombreprovincia = nombreprovincia;
    }
    public Provincia(int idprovincia, String nombreprovincia, Set localidads) {
       this.idprovincia = idprovincia;
       this.nombreprovincia = nombreprovincia;
       this.localidads = localidads;
    }
   
     @Id 

    
    @Column(name="idprovincia", unique=true, nullable=false)
    public int getIdprovincia() {
        return this.idprovincia;
    }
    
    public void setIdprovincia(int idprovincia) {
        this.idprovincia = idprovincia;
    }

    
    @Column(name="nombreprovincia", nullable=false, length=30)
    public String getNombreprovincia() {
        return this.nombreprovincia;
    }
    
    public void setNombreprovincia(String nombreprovincia) {
        this.nombreprovincia = nombreprovincia;
    }
    
@OneToMany(fetch=FetchType.LAZY, mappedBy="provincia")
    public Set getLocalidads() {
        return this.localidads;
    }
    
    public void setLocalidads(Set localidads) {
        this.localidads = localidads;
    }




}


