package org.blh.habilitacion.entities;
// Generated 30-jun-2015 0:45:21 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Seguimientobebeasociado generated by hbm2java
 */
@Entity
@Table(name="seguimientobebeasociado"
    ,schema="public"
)
public class Seguimientobebeasociado  implements java.io.Serializable {


     private SeguimientobebeasociadoId id;
     private Bebeasociado bebeasociado;
     private Date fechSegBebeAsociado;
     private String doctor;
     private String alturaBebeAsociado;
     private String pesoBebeAsociado;
     private String perimetroEncefalicoBebeAsociado;
     private String observacionesBebeAsoc;

    public Seguimientobebeasociado() {
    }

	
    public Seguimientobebeasociado(SeguimientobebeasociadoId id, Bebeasociado bebeasociado, String alturaBebeAsociado, String pesoBebeAsociado, String perimetroEncefalicoBebeAsociado) {
        this.id = id;
        this.bebeasociado = bebeasociado;
        this.alturaBebeAsociado = alturaBebeAsociado;
        this.pesoBebeAsociado = pesoBebeAsociado;
        this.perimetroEncefalicoBebeAsociado = perimetroEncefalicoBebeAsociado;
    }
    public Seguimientobebeasociado(SeguimientobebeasociadoId id, Bebeasociado bebeasociado, Date fechSegBebeAsociado, String doctor, String alturaBebeAsociado, String pesoBebeAsociado, String perimetroEncefalicoBebeAsociado, String observacionesBebeAsoc) {
       this.id = id;
       this.bebeasociado = bebeasociado;
       this.fechSegBebeAsociado = fechSegBebeAsociado;
       this.doctor = doctor;
       this.alturaBebeAsociado = alturaBebeAsociado;
       this.pesoBebeAsociado = pesoBebeAsociado;
       this.perimetroEncefalicoBebeAsociado = perimetroEncefalicoBebeAsociado;
       this.observacionesBebeAsoc = observacionesBebeAsoc;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idSeguimiento", column=@Column(name="IdSeguimiento", nullable=false) ), 
        @AttributeOverride(name="idBebeAosciado", column=@Column(name="idBebeAosciado", nullable=false) ), 
        @AttributeOverride(name="nroConcentimiento", column=@Column(name="nroConcentimiento", nullable=false) ) } )
    public SeguimientobebeasociadoId getId() {
        return this.id;
    }
    
    public void setId(SeguimientobebeasociadoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="idBebeAosciado", referencedColumnName="idBebeAosciado", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="nroConcentimiento", referencedColumnName="nroConcentimiento", nullable=false, insertable=false, updatable=false) } )
    public Bebeasociado getBebeasociado() {
        return this.bebeasociado;
    }
    
    public void setBebeasociado(Bebeasociado bebeasociado) {
        this.bebeasociado = bebeasociado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechSegBebeAsociado", length=13)
    public Date getFechSegBebeAsociado() {
        return this.fechSegBebeAsociado;
    }
    
    public void setFechSegBebeAsociado(Date fechSegBebeAsociado) {
        this.fechSegBebeAsociado = fechSegBebeAsociado;
    }

    
    @Column(name="doctor", length=25)
    public String getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(String doctor) {
        this.doctor = doctor;
    }

    
    @Column(name="alturaBebeAsociado", nullable=false, length=10)
    public String getAlturaBebeAsociado() {
        return this.alturaBebeAsociado;
    }
    
    public void setAlturaBebeAsociado(String alturaBebeAsociado) {
        this.alturaBebeAsociado = alturaBebeAsociado;
    }

    
    @Column(name="pesoBebeAsociado", nullable=false, length=10)
    public String getPesoBebeAsociado() {
        return this.pesoBebeAsociado;
    }
    
    public void setPesoBebeAsociado(String pesoBebeAsociado) {
        this.pesoBebeAsociado = pesoBebeAsociado;
    }

    
    @Column(name="perimetroEncefalicoBebeAsociado", nullable=false, length=10)
    public String getPerimetroEncefalicoBebeAsociado() {
        return this.perimetroEncefalicoBebeAsociado;
    }
    
    public void setPerimetroEncefalicoBebeAsociado(String perimetroEncefalicoBebeAsociado) {
        this.perimetroEncefalicoBebeAsociado = perimetroEncefalicoBebeAsociado;
    }

    
    @Column(name="observacionesBebeAsoc", length=50)
    public String getObservacionesBebeAsoc() {
        return this.observacionesBebeAsoc;
    }
    
    public void setObservacionesBebeAsoc(String observacionesBebeAsoc) {
        this.observacionesBebeAsoc = observacionesBebeAsoc;
    }




}


