package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Seguimientobebeasociado generated by hbm2java
 */
@Entity
@Table(name="seguimientobebeasociado"
    ,schema="public"
)
public class Seguimientobebeasociado  implements java.io.Serializable {


     private SeguimientobebeasociadoId id;
     private Bebeasociado bebeasociado;
     private Date fechsegbebeasociado;
     private String doctor;
     private String alturabebeasociado;
     private String pesobebeasociado;
     private String perimetroencefalicobebeasociado;
     private String observacionesbebeasoc;

    public Seguimientobebeasociado() {
    }

	
    public Seguimientobebeasociado(SeguimientobebeasociadoId id, Bebeasociado bebeasociado, String alturabebeasociado, String pesobebeasociado, String perimetroencefalicobebeasociado) {
        this.id = id;
        this.bebeasociado = bebeasociado;
        this.alturabebeasociado = alturabebeasociado;
        this.pesobebeasociado = pesobebeasociado;
        this.perimetroencefalicobebeasociado = perimetroencefalicobebeasociado;
    }
    public Seguimientobebeasociado(SeguimientobebeasociadoId id, Bebeasociado bebeasociado, Date fechsegbebeasociado, String doctor, String alturabebeasociado, String pesobebeasociado, String perimetroencefalicobebeasociado, String observacionesbebeasoc) {
       this.id = id;
       this.bebeasociado = bebeasociado;
       this.fechsegbebeasociado = fechsegbebeasociado;
       this.doctor = doctor;
       this.alturabebeasociado = alturabebeasociado;
       this.pesobebeasociado = pesobebeasociado;
       this.perimetroencefalicobebeasociado = perimetroencefalicobebeasociado;
       this.observacionesbebeasoc = observacionesbebeasoc;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idseguimiento", column=@Column(name="Idseguimiento", nullable=false) ), 
        @AttributeOverride(name="idbebeasociado", column=@Column(name="idbebeasociado", nullable=false) ), 
        @AttributeOverride(name="nroconcentimiento", column=@Column(name="nroconcentimiento", nullable=false) ) } )
    public SeguimientobebeasociadoId getId() {
        return this.id;
    }
    
    public void setId(SeguimientobebeasociadoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="idbebeasociado", referencedColumnName="idbebeasociado", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="nroconcentimiento", referencedColumnName="nroconcentimiento", nullable=false, insertable=false, updatable=false) } )
    public Bebeasociado getBebeasociado() {
        return this.bebeasociado;
    }
    
    public void setBebeasociado(Bebeasociado bebeasociado) {
        this.bebeasociado = bebeasociado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechsegbebeasociado", length=13)
    public Date getFechsegbebeasociado() {
        return this.fechsegbebeasociado;
    }
    
    public void setFechsegbebeasociado(Date fechsegbebeasociado) {
        this.fechsegbebeasociado = fechsegbebeasociado;
    }

    
    @Column(name="doctor", length=25)
    public String getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(String doctor) {
        this.doctor = doctor;
    }

    
    @Column(name="alturabebeasociado", nullable=false, length=10)
    public String getAlturabebeasociado() {
        return this.alturabebeasociado;
    }
    
    public void setAlturabebeasociado(String alturabebeasociado) {
        this.alturabebeasociado = alturabebeasociado;
    }

    
    @Column(name="pesobebeasociado", nullable=false, length=10)
    public String getPesobebeasociado() {
        return this.pesobebeasociado;
    }
    
    public void setPesobebeasociado(String pesobebeasociado) {
        this.pesobebeasociado = pesobebeasociado;
    }

    
    @Column(name="perimetroencefalicobebeasociado", nullable=false, length=10)
    public String getPerimetroencefalicobebeasociado() {
        return this.perimetroencefalicobebeasociado;
    }
    
    public void setPerimetroencefalicobebeasociado(String perimetroencefalicobebeasociado) {
        this.perimetroencefalicobebeasociado = perimetroencefalicobebeasociado;
    }

    
    @Column(name="observacionesbebeasoc", length=50)
    public String getObservacionesbebeasoc() {
        return this.observacionesbebeasoc;
    }
    
    public void setObservacionesbebeasoc(String observacionesbebeasoc) {
        this.observacionesbebeasoc = observacionesbebeasoc;
    }




}


