package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Seguimientobebereceptor generated by hbm2java
 */
@Entity
@Table(name="seguimientobebereceptor"
    ,schema="public"
)
public class Seguimientobebereceptor  implements java.io.Serializable {


     private SeguimientobebereceptorId id;
     private Bebereceptor bebereceptor;
     private Date fechsegbebereceptor;
     private Integer edadgestacionalbebereceptor;
     private Double tallabebereceptor;
     private Double pesobebereceptor;
     private Double perimetroencefalicobebereceptor;
     private String observaciones;

    public Seguimientobebereceptor() {
    }

	
    public Seguimientobebereceptor(SeguimientobebereceptorId id, Bebereceptor bebereceptor) {
        this.id = id;
        this.bebereceptor = bebereceptor;
    }
    public Seguimientobebereceptor(SeguimientobebereceptorId id, Bebereceptor bebereceptor, Date fechsegbebereceptor, Integer edadgestacionalbebereceptor, Double tallabebereceptor, Double pesobebereceptor, Double perimetroencefalicobebereceptor, String observaciones) {
       this.id = id;
       this.bebereceptor = bebereceptor;
       this.fechsegbebereceptor = fechsegbebereceptor;
       this.edadgestacionalbebereceptor = edadgestacionalbebereceptor;
       this.tallabebereceptor = tallabebereceptor;
       this.pesobebereceptor = pesobebereceptor;
       this.perimetroencefalicobebereceptor = perimetroencefalicobebereceptor;
       this.observaciones = observaciones;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idsegbebereceptor", column=@Column(name="idsegbebereceptor", nullable=false) ), 
        @AttributeOverride(name="idbebereceptor", column=@Column(name="idbebereceptor", nullable=false) ) } )
    public SeguimientobebereceptorId getId() {
        return this.id;
    }
    
    public void setId(SeguimientobebereceptorId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idbebereceptor", nullable=false, insertable=false, updatable=false)
    public Bebereceptor getBebereceptor() {
        return this.bebereceptor;
    }
    
    public void setBebereceptor(Bebereceptor bebereceptor) {
        this.bebereceptor = bebereceptor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechsegbebereceptor", length=13)
    public Date getFechsegbebereceptor() {
        return this.fechsegbebereceptor;
    }
    
    public void setFechsegbebereceptor(Date fechsegbebereceptor) {
        this.fechsegbebereceptor = fechsegbebereceptor;
    }

    
    @Column(name="edadgestacionalbebereceptor")
    public Integer getEdadgestacionalbebereceptor() {
        return this.edadgestacionalbebereceptor;
    }
    
    public void setEdadgestacionalbebereceptor(Integer edadgestacionalbebereceptor) {
        this.edadgestacionalbebereceptor = edadgestacionalbebereceptor;
    }

    
    @Column(name="tallabebereceptor", precision=17, scale=17)
    public Double getTallabebereceptor() {
        return this.tallabebereceptor;
    }
    
    public void setTallabebereceptor(Double tallabebereceptor) {
        this.tallabebereceptor = tallabebereceptor;
    }

    
    @Column(name="pesobebereceptor", precision=17, scale=17)
    public Double getPesobebereceptor() {
        return this.pesobebereceptor;
    }
    
    public void setPesobebereceptor(Double pesobebereceptor) {
        this.pesobebereceptor = pesobebereceptor;
    }

    
    @Column(name="perimetroencefalicobebereceptor", precision=17, scale=17)
    public Double getPerimetroencefalicobebereceptor() {
        return this.perimetroencefalicobebereceptor;
    }
    
    public void setPerimetroencefalicobebereceptor(Double perimetroencefalicobebereceptor) {
        this.perimetroencefalicobebereceptor = perimetroencefalicobebereceptor;
    }

    
    @Column(name="observaciones", length=50)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


