package org.blh.habilitacion.entities;
// Generated 30-jun-2015 0:45:21 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Seguimientobebereceptor generated by hbm2java
 */
@Entity
@Table(name="seguimientobebereceptor"
    ,schema="public"
)
public class Seguimientobebereceptor  implements java.io.Serializable {


     private SeguimientobebereceptorId id;
     private Bebereceptor bebereceptor;
     private Date fechSegBebeReceptor;
     private Integer edadGestacionalBebeReceptor;
     private Double tallaBebeReceptor;
     private Double pesoBebeReceptor;
     private Double perimetroEncefalicoBebeReceptor;
     private String observaciones;

    public Seguimientobebereceptor() {
    }

	
    public Seguimientobebereceptor(SeguimientobebereceptorId id, Bebereceptor bebereceptor) {
        this.id = id;
        this.bebereceptor = bebereceptor;
    }
    public Seguimientobebereceptor(SeguimientobebereceptorId id, Bebereceptor bebereceptor, Date fechSegBebeReceptor, Integer edadGestacionalBebeReceptor, Double tallaBebeReceptor, Double pesoBebeReceptor, Double perimetroEncefalicoBebeReceptor, String observaciones) {
       this.id = id;
       this.bebereceptor = bebereceptor;
       this.fechSegBebeReceptor = fechSegBebeReceptor;
       this.edadGestacionalBebeReceptor = edadGestacionalBebeReceptor;
       this.tallaBebeReceptor = tallaBebeReceptor;
       this.pesoBebeReceptor = pesoBebeReceptor;
       this.perimetroEncefalicoBebeReceptor = perimetroEncefalicoBebeReceptor;
       this.observaciones = observaciones;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idSegBebeReceptor", column=@Column(name="idSegBebeReceptor", nullable=false) ), 
        @AttributeOverride(name="idBebeReceptor", column=@Column(name="idBebeReceptor", nullable=false) ) } )
    public SeguimientobebereceptorId getId() {
        return this.id;
    }
    
    public void setId(SeguimientobebereceptorId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idBebeReceptor", nullable=false, insertable=false, updatable=false)
    public Bebereceptor getBebereceptor() {
        return this.bebereceptor;
    }
    
    public void setBebereceptor(Bebereceptor bebereceptor) {
        this.bebereceptor = bebereceptor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechSegBebeReceptor", length=13)
    public Date getFechSegBebeReceptor() {
        return this.fechSegBebeReceptor;
    }
    
    public void setFechSegBebeReceptor(Date fechSegBebeReceptor) {
        this.fechSegBebeReceptor = fechSegBebeReceptor;
    }

    
    @Column(name="edadGestacionalBebeReceptor")
    public Integer getEdadGestacionalBebeReceptor() {
        return this.edadGestacionalBebeReceptor;
    }
    
    public void setEdadGestacionalBebeReceptor(Integer edadGestacionalBebeReceptor) {
        this.edadGestacionalBebeReceptor = edadGestacionalBebeReceptor;
    }

    
    @Column(name="tallaBebeReceptor", precision=17, scale=17)
    public Double getTallaBebeReceptor() {
        return this.tallaBebeReceptor;
    }
    
    public void setTallaBebeReceptor(Double tallaBebeReceptor) {
        this.tallaBebeReceptor = tallaBebeReceptor;
    }

    
    @Column(name="pesoBebeReceptor", precision=17, scale=17)
    public Double getPesoBebeReceptor() {
        return this.pesoBebeReceptor;
    }
    
    public void setPesoBebeReceptor(Double pesoBebeReceptor) {
        this.pesoBebeReceptor = pesoBebeReceptor;
    }

    
    @Column(name="perimetroEncefalicoBebeReceptor", precision=17, scale=17)
    public Double getPerimetroEncefalicoBebeReceptor() {
        return this.perimetroEncefalicoBebeReceptor;
    }
    
    public void setPerimetroEncefalicoBebeReceptor(Double perimetroEncefalicoBebeReceptor) {
        this.perimetroEncefalicoBebeReceptor = perimetroEncefalicoBebeReceptor;
    }

    
    @Column(name="observaciones", length=50)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


