package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SeguimientobebereceptorId generated by hbm2java
 */
@Embeddable
public class SeguimientobebereceptorId  implements java.io.Serializable {


     private int idsegbebereceptor;
     private int idbebereceptor;

    public SeguimientobebereceptorId() {
    }

    public SeguimientobebereceptorId(int idsegbebereceptor, int idbebereceptor) {
       this.idsegbebereceptor = idsegbebereceptor;
       this.idbebereceptor = idbebereceptor;
    }
   


    @Column(name="idsegbebereceptor", nullable=false)
    public int getIdsegbebereceptor() {
        return this.idsegbebereceptor;
    }
    
    public void setIdsegbebereceptor(int idsegbebereceptor) {
        this.idsegbebereceptor = idsegbebereceptor;
    }


    @Column(name="idbebereceptor", nullable=false)
    public int getIdbebereceptor() {
        return this.idbebereceptor;
    }
    
    public void setIdbebereceptor(int idbebereceptor) {
        this.idbebereceptor = idbebereceptor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SeguimientobebereceptorId) ) return false;
		 SeguimientobebereceptorId castOther = ( SeguimientobebereceptorId ) other; 
         
		 return (this.getIdsegbebereceptor()==castOther.getIdsegbebereceptor())
 && (this.getIdbebereceptor()==castOther.getIdbebereceptor());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdsegbebereceptor();
         result = 37 * result + this.getIdbebereceptor();
         return result;
   }   


}


