package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SerologiaId generated by hbm2java
 */
@Embeddable
public class SerologiaId  implements java.io.Serializable {


     private int nroserologia;
     private int nroconcentimiento;

    public SerologiaId() {
    }

    public SerologiaId(int nroserologia, int nroconcentimiento) {
       this.nroserologia = nroserologia;
       this.nroconcentimiento = nroconcentimiento;
    }
   


    @Column(name="nroserologia", nullable=false)
    public int getNroserologia() {
        return this.nroserologia;
    }
    
    public void setNroserologia(int nroserologia) {
        this.nroserologia = nroserologia;
    }


    @Column(name="nroconcentimiento", nullable=false)
    public int getNroconcentimiento() {
        return this.nroconcentimiento;
    }
    
    public void setNroconcentimiento(int nroconcentimiento) {
        this.nroconcentimiento = nroconcentimiento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SerologiaId) ) return false;
		 SerologiaId castOther = ( SerologiaId ) other; 
         
		 return (this.getNroserologia()==castOther.getNroserologia())
 && (this.getNroconcentimiento()==castOther.getNroconcentimiento());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNroserologia();
         result = 37 * result + this.getNroconcentimiento();
         return result;
   }   


}


