package org.blh.habilitacion.entities;
// Generated 30-jun-2015 0:45:21 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Serologia generated by hbm2java
 */
@Entity
@Table(name="serologia"
    ,schema="public"
)
public class Serologia  implements java.io.Serializable {


     private SerologiaId id;
     private Consentimiento consentimiento;
     private Date fechaSerologia;
     private Date fechaCarga;
     private boolean vdrl;
     private Boolean chagas;
     private Boolean hvc;
     private Boolean hiv;
     private Boolean hvb;
     private Boolean hvbCore;
     private Boolean toxoplasmosis;
     private Boolean htlvlIi;
     private Boolean medicacion;
     private Boolean fuma;
     private Boolean usaDrogas;
     private Boolean alcohol;
     private Boolean zonaRural;
     private Boolean vacunas;
     private String igM;
     private String igG;
     private String droga;
     private String dosis;
     private String resultadoSerologia;
     private String observaciones;

    public Serologia() {
    }

	
    public Serologia(SerologiaId id, Consentimiento consentimiento, boolean vdrl, String dosis) {
        this.id = id;
        this.consentimiento = consentimiento;
        this.vdrl = vdrl;
        this.dosis = dosis;
    }
    public Serologia(SerologiaId id, Consentimiento consentimiento, Date fechaSerologia, Date fechaCarga, boolean vdrl, Boolean chagas, Boolean hvc, Boolean hiv, Boolean hvb, Boolean hvbCore, Boolean toxoplasmosis, Boolean htlvlIi, Boolean medicacion, Boolean fuma, Boolean usaDrogas, Boolean alcohol, Boolean zonaRural, Boolean vacunas, String igM, String igG, String droga, String dosis, String resultadoSerologia, String observaciones) {
       this.id = id;
       this.consentimiento = consentimiento;
       this.fechaSerologia = fechaSerologia;
       this.fechaCarga = fechaCarga;
       this.vdrl = vdrl;
       this.chagas = chagas;
       this.hvc = hvc;
       this.hiv = hiv;
       this.hvb = hvb;
       this.hvbCore = hvbCore;
       this.toxoplasmosis = toxoplasmosis;
       this.htlvlIi = htlvlIi;
       this.medicacion = medicacion;
       this.fuma = fuma;
       this.usaDrogas = usaDrogas;
       this.alcohol = alcohol;
       this.zonaRural = zonaRural;
       this.vacunas = vacunas;
       this.igM = igM;
       this.igG = igG;
       this.droga = droga;
       this.dosis = dosis;
       this.resultadoSerologia = resultadoSerologia;
       this.observaciones = observaciones;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="nroSerologia", column=@Column(name="nroSerologia", nullable=false) ), 
        @AttributeOverride(name="nroConcentimiento", column=@Column(name="nroConcentimiento", nullable=false) ) } )
    public SerologiaId getId() {
        return this.id;
    }
    
    public void setId(SerologiaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nroConcentimiento", nullable=false, insertable=false, updatable=false)
    public Consentimiento getConsentimiento() {
        return this.consentimiento;
    }
    
    public void setConsentimiento(Consentimiento consentimiento) {
        this.consentimiento = consentimiento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaSerologia", length=13)
    public Date getFechaSerologia() {
        return this.fechaSerologia;
    }
    
    public void setFechaSerologia(Date fechaSerologia) {
        this.fechaSerologia = fechaSerologia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaCarga", length=13)
    public Date getFechaCarga() {
        return this.fechaCarga;
    }
    
    public void setFechaCarga(Date fechaCarga) {
        this.fechaCarga = fechaCarga;
    }

    
    @Column(name="vdrl", nullable=false)
    public boolean isVdrl() {
        return this.vdrl;
    }
    
    public void setVdrl(boolean vdrl) {
        this.vdrl = vdrl;
    }

    
    @Column(name="chagas")
    public Boolean getChagas() {
        return this.chagas;
    }
    
    public void setChagas(Boolean chagas) {
        this.chagas = chagas;
    }

    
    @Column(name="hvc")
    public Boolean getHvc() {
        return this.hvc;
    }
    
    public void setHvc(Boolean hvc) {
        this.hvc = hvc;
    }

    
    @Column(name="hiv")
    public Boolean getHiv() {
        return this.hiv;
    }
    
    public void setHiv(Boolean hiv) {
        this.hiv = hiv;
    }

    
    @Column(name="hvb")
    public Boolean getHvb() {
        return this.hvb;
    }
    
    public void setHvb(Boolean hvb) {
        this.hvb = hvb;
    }

    
    @Column(name="hvbCore")
    public Boolean getHvbCore() {
        return this.hvbCore;
    }
    
    public void setHvbCore(Boolean hvbCore) {
        this.hvbCore = hvbCore;
    }

    
    @Column(name="toxoplasmosis")
    public Boolean getToxoplasmosis() {
        return this.toxoplasmosis;
    }
    
    public void setToxoplasmosis(Boolean toxoplasmosis) {
        this.toxoplasmosis = toxoplasmosis;
    }

    
    @Column(name="htlvl_II")
    public Boolean getHtlvlIi() {
        return this.htlvlIi;
    }
    
    public void setHtlvlIi(Boolean htlvlIi) {
        this.htlvlIi = htlvlIi;
    }

    
    @Column(name="medicacion")
    public Boolean getMedicacion() {
        return this.medicacion;
    }
    
    public void setMedicacion(Boolean medicacion) {
        this.medicacion = medicacion;
    }

    
    @Column(name="fuma")
    public Boolean getFuma() {
        return this.fuma;
    }
    
    public void setFuma(Boolean fuma) {
        this.fuma = fuma;
    }

    
    @Column(name="usaDrogas")
    public Boolean getUsaDrogas() {
        return this.usaDrogas;
    }
    
    public void setUsaDrogas(Boolean usaDrogas) {
        this.usaDrogas = usaDrogas;
    }

    
    @Column(name="alcohol")
    public Boolean getAlcohol() {
        return this.alcohol;
    }
    
    public void setAlcohol(Boolean alcohol) {
        this.alcohol = alcohol;
    }

    
    @Column(name="zonaRural")
    public Boolean getZonaRural() {
        return this.zonaRural;
    }
    
    public void setZonaRural(Boolean zonaRural) {
        this.zonaRural = zonaRural;
    }

    
    @Column(name="vacunas")
    public Boolean getVacunas() {
        return this.vacunas;
    }
    
    public void setVacunas(Boolean vacunas) {
        this.vacunas = vacunas;
    }

    
    @Column(name="igM", length=10)
    public String getIgM() {
        return this.igM;
    }
    
    public void setIgM(String igM) {
        this.igM = igM;
    }

    
    @Column(name="igG", length=10)
    public String getIgG() {
        return this.igG;
    }
    
    public void setIgG(String igG) {
        this.igG = igG;
    }

    
    @Column(name="droga", length=18)
    public String getDroga() {
        return this.droga;
    }
    
    public void setDroga(String droga) {
        this.droga = droga;
    }

    
    @Column(name="dosis", nullable=false, length=10)
    public String getDosis() {
        return this.dosis;
    }
    
    public void setDosis(String dosis) {
        this.dosis = dosis;
    }

    
    @Column(name="resultadoSerologia", length=15)
    public String getResultadoSerologia() {
        return this.resultadoSerologia;
    }
    
    public void setResultadoSerologia(String resultadoSerologia) {
        this.resultadoSerologia = resultadoSerologia;
    }

    
    @Column(name="observaciones", length=10)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


