package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private UsuarioId id;
     private Perfil perfil;
     private String username;
     private String password;
     private Date ultimaFechaConection;

    public Usuario() {
    }

	
    public Usuario(UsuarioId id, Perfil perfil) {
        this.id = id;
        this.perfil = perfil;
    }
    public Usuario(UsuarioId id, Perfil perfil, String username, String password, Date ultimaFechaConection) {
       this.id = id;
       this.perfil = perfil;
       this.username = username;
       this.password = password;
       this.ultimaFechaConection = ultimaFechaConection;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idPerfil", column=@Column(name="idPerfil", nullable=false) ), 
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ) } )
    public UsuarioId getId() {
        return this.id;
    }
    
    public void setId(UsuarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id", nullable=false, insertable=false, updatable=false)
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

    
    @Column(name="username", length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ultima_fecha_conection", length=13)
    public Date getUltimaFechaConection() {
        return this.ultimaFechaConection;
    }
    
    public void setUltimaFechaConection(Date ultimaFechaConection) {
        this.ultimaFechaConection = ultimaFechaConection;
    }




}


