package org.blh.habilitacion.entities;
// Generated 06-jul-2015 22:01:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Zona generated by hbm2java
 */
@Entity
@Table(name="zona"
    ,schema="public"
)
public class Zona  implements java.io.Serializable {


     private ZonaId id;
     private Localidad localidad;
     private String nombrezona;
     private boolean estadozona;
     private Boolean lunes;
     private Boolean martes;
     private Boolean miercoles;
     private Boolean jueves;
     private Boolean viernes;
     private Set consentimientos = new HashSet(0);

    public Zona() {
    }

	
    public Zona(ZonaId id, Localidad localidad, String nombrezona, boolean estadozona) {
        this.id = id;
        this.localidad = localidad;
        this.nombrezona = nombrezona;
        this.estadozona = estadozona;
    }
    public Zona(ZonaId id, Localidad localidad, String nombrezona, boolean estadozona, Boolean lunes, Boolean martes, Boolean miercoles, Boolean jueves, Boolean viernes, Set consentimientos) {
       this.id = id;
       this.localidad = localidad;
       this.nombrezona = nombrezona;
       this.estadozona = estadozona;
       this.lunes = lunes;
       this.martes = martes;
       this.miercoles = miercoles;
       this.jueves = jueves;
       this.viernes = viernes;
       this.consentimientos = consentimientos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idzona", column=@Column(name="idzona", nullable=false) ), 
        @AttributeOverride(name="idlocalidad", column=@Column(name="idlocalidad", nullable=false) ), 
        @AttributeOverride(name="idprovincia", column=@Column(name="idprovincia", nullable=false) ) } )
    public ZonaId getId() {
        return this.id;
    }
    
    public void setId(ZonaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="idlocalidad", referencedColumnName="idlocalidad", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="idprovincia", referencedColumnName="idprovincia", nullable=false, insertable=false, updatable=false) } )
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }

    
    @Column(name="nombrezona", nullable=false, length=30)
    public String getNombrezona() {
        return this.nombrezona;
    }
    
    public void setNombrezona(String nombrezona) {
        this.nombrezona = nombrezona;
    }

    
    @Column(name="estadozona", nullable=false)
    public boolean isEstadozona() {
        return this.estadozona;
    }
    
    public void setEstadozona(boolean estadozona) {
        this.estadozona = estadozona;
    }

    
    @Column(name="lunes")
    public Boolean getLunes() {
        return this.lunes;
    }
    
    public void setLunes(Boolean lunes) {
        this.lunes = lunes;
    }

    
    @Column(name="martes")
    public Boolean getMartes() {
        return this.martes;
    }
    
    public void setMartes(Boolean martes) {
        this.martes = martes;
    }

    
    @Column(name="miercoles")
    public Boolean getMiercoles() {
        return this.miercoles;
    }
    
    public void setMiercoles(Boolean miercoles) {
        this.miercoles = miercoles;
    }

    
    @Column(name="jueves")
    public Boolean getJueves() {
        return this.jueves;
    }
    
    public void setJueves(Boolean jueves) {
        this.jueves = jueves;
    }

    
    @Column(name="viernes")
    public Boolean getViernes() {
        return this.viernes;
    }
    
    public void setViernes(Boolean viernes) {
        this.viernes = viernes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="zona")
    public Set getConsentimientos() {
        return this.consentimientos;
    }
    
    public void setConsentimientos(Set consentimientos) {
        this.consentimientos = consentimientos;
    }




}


