package org.blh.habilitacion.entities;
// Generated 30-jun-2015 0:45:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Zona generated by hbm2java
 */
@Entity
@Table(name="zona"
    ,schema="public"
)
public class Zona  implements java.io.Serializable {


     private int idZona;
     private Localidad localidad;
     private String nombreZona;
     private boolean estadoZona;
     private Boolean lunes;
     private Boolean martes;
     private Boolean miercoles;
     private Boolean jueves;
     private Boolean viernes;
     private Set consentimientos = new HashSet(0);

    public Zona() {
    }

	
    public Zona(int idZona, Localidad localidad, String nombreZona, boolean estadoZona) {
        this.idZona = idZona;
        this.localidad = localidad;
        this.nombreZona = nombreZona;
        this.estadoZona = estadoZona;
    }
    public Zona(int idZona, Localidad localidad, String nombreZona, boolean estadoZona, Boolean lunes, Boolean martes, Boolean miercoles, Boolean jueves, Boolean viernes, Set consentimientos) {
       this.idZona = idZona;
       this.localidad = localidad;
       this.nombreZona = nombreZona;
       this.estadoZona = estadoZona;
       this.lunes = lunes;
       this.martes = martes;
       this.miercoles = miercoles;
       this.jueves = jueves;
       this.viernes = viernes;
       this.consentimientos = consentimientos;
    }
   
     @Id 

    
    @Column(name="idZona", nullable=false)
    public int getIdZona() {
        return this.idZona;
    }
    
    public void setIdZona(int idZona) {
        this.idZona = idZona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLocalidad", nullable=false)
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }

    
    @Column(name="nombreZona", nullable=false, length=30)
    public String getNombreZona() {
        return this.nombreZona;
    }
    
    public void setNombreZona(String nombreZona) {
        this.nombreZona = nombreZona;
    }

    
    @Column(name="estadoZona", nullable=false)
    public boolean isEstadoZona() {
        return this.estadoZona;
    }
    
    public void setEstadoZona(boolean estadoZona) {
        this.estadoZona = estadoZona;
    }

    
    @Column(name="lunes")
    public Boolean getLunes() {
        return this.lunes;
    }
    
    public void setLunes(Boolean lunes) {
        this.lunes = lunes;
    }

    
    @Column(name="martes")
    public Boolean getMartes() {
        return this.martes;
    }
    
    public void setMartes(Boolean martes) {
        this.martes = martes;
    }

    
    @Column(name="miercoles")
    public Boolean getMiercoles() {
        return this.miercoles;
    }
    
    public void setMiercoles(Boolean miercoles) {
        this.miercoles = miercoles;
    }

    
    @Column(name="jueves")
    public Boolean getJueves() {
        return this.jueves;
    }
    
    public void setJueves(Boolean jueves) {
        this.jueves = jueves;
    }

    
    @Column(name="viernes")
    public Boolean getViernes() {
        return this.viernes;
    }
    
    public void setViernes(Boolean viernes) {
        this.viernes = viernes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="zona")
    public Set getConsentimientos() {
        return this.consentimientos;
    }
    
    public void setConsentimientos(Set consentimientos) {
        this.consentimientos = consentimientos;
    }




}


